/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reputation/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة الدفتر بمُرشِّح إلزامي
         * @description مُرشِّح واحد على الأقل مطلوب (`subjectPublicId` أو `orderPublicId`): دفترٌ يُقرأ بلا
         *     مُرشِّح يعني تصديرَ سلوك كل الناس بطلبٍ واحد. والقراءة أحدثُ الوقائع أولاً لأن السؤال
         *     المعتاد «ماذا جرى أخيراً؟».
         */
        get: operations["listReputationFacts"];
        put?: never;
        /**
         * تسجيل واقعةٍ مُشتقّة من حدثٍ منشور
         * @description المدخل الوحيد إلى الدفتر، ويستدعيه مستهلكُ أحداث محرّك الطلب (المراجعة 5/6). الحمولة
         *     **تحمل مصدرها**: نوع الحدث ومُعرّفه وترتيبه على الطلب (`source_sequence`). وإعادةُ نفس
         *     المصدر تُعيد الواقعة نفسها بـ`200` بلا صفٍّ ثانٍ ولا نقطةٍ مضاعفة — القيد
         *     `ux_reputation_facts_source` في القاعدة هو الحارس، لا فحصٌ في الكود يسقط بأوّل تشغيلٍ متوازٍ.
         *
         *     وتسجيلُ الواقعة يجرّ إعادة حساب النتيجة في **نفس المعاملة**: نقطةٌ تتخلّف عن واقعتها
         *     تجعل القراءة تكذب بين لحظتين.
         */
        post: operations["recordReputationFact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/scores/{subjectType}/{subjectPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة نتيجة شخصٍ ورتبته
         * @description `404` لمن لا وقائع له، لا نتيجةٌ افتراضية: **نقاطٌ مُختلَقة لغريبٍ أسوأ من غيابها** —
         *     مستهلكٌ يرى 60 لا يعرف أهي حصيلةُ عملٍ أم قيمةُ بدايةٍ لمن لم يعمل. والحمولة تحمل
         *     `ruleset_version` و`fact_count` و`computed_at` كي يكشف القارئ حساباً قديماً بلا سؤال.
         */
        get: operations["getReputationScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/scores/{subjectType}/{subjectPublicId}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إعادة بناء النتيجة من الدفتر وحده
         * @description الطريق الذي يجعل القرار 3 قابلاً للتنفيذ لا شعاراً: النتيجة **مُشتقّة**، وحذفُها بالكامل
         *     عملٌ بلا خسارة لأن هذا المسار يُعيدها كما كانت من الوقائع ونسخة القواعد. لا `requestBody`
         *     عمداً: الفعل على الحالة المخزّنة، وإعلان جسمٍ فارغ يجعل الخادم يرفض طلباً صحيحاً بـ`400`.
         *
         *     و`404` لمن لا وقائع له: لا يُختلق دفترٌ لمن لم يُعامل النظام.
         */
        post: operations["recomputeReputationScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة التقييمات بمُرشِّح إلزامي
         * @description مُرشِّح واحد على الأقل مطلوب (`subjectPublicId` أو `orderPublicId`). والدرجات تُعاد كما
         *     سُجّلت بلا متوسّطٍ محسوب هنا: المتوسّط يعيش في النتيجة بقواعدها، وحسابُه في مسارٍ ثانٍ
         *     يُنشئ رقمين يختلفان.
         */
        get: operations["listReputationRatings"];
        put?: never;
        /**
         * تسجيل تقييمٍ على طلبٍ اكتمل
         * @description التقييم **حقٌّ يُشتقّ من واقعة** لا مدخلٌ حرّ: يُرفض إن لم تكن للطلب واقعةُ اكتمالٍ في
         *     الدفتر (`REPUTATION_ORDER_NOT_COMPLETED`)، أو مضت نافذة `rating_window_hours`
         *     (`REPUTATION_RATING_WINDOW_CLOSED`)، أو كان المُقيِّم هو المُقيَّم
         *     (`REPUTATION_RATING_SELF_FORBIDDEN`).
         *
         *     ودرجةٌ ورمزُ سبب فقط: **لا حقل تعليق في هذا العقد** (القرار 5). والتقييم لا يكتب نقاطاً
         *     بنفسه بل يُنتج واقعةً من نوع `rating_received`، فيبقى للنقطة مصدرٌ واحد الشكل.
         */
        post: operations["submitReputationRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/fraud-signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة إشارات الاحتيال
         * @description قراءةٌ فقط: لا مسار يُنشئ إشارةً يدوياً (تُنشَأ من الوقائع في النبضة)، ولا مسار يبتّ فيها
         *     (مراجعةٌ بشرية لا يملكها هذا الطور — القرار 6). وكل إشارةٍ تُعيد قاعدتها ونافذتها وعددها
         *     وعتبتها ونسخةَ قواعدها: إشارةٌ لا تشرح نفسها لا يمكن الردّ عليها.
         */
        get: operations["listFraudSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة نسخ القواعد */
        get: operations["listReputationRulesets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/rulesets/{rulesetVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة نسخة قواعد بأوزانها وعتباتها
         * @description الأوزان والعتبات **مُعلَنة للقراءة** لا مخفيّة في الكود: من يريد أن يشرح لسائقٍ لماذا نقصت
         *     نقاطه يحتاج القاعدة نفسها، وليس وصفاً لها في وثيقة قد تتخلّف.
         */
        get: operations["getReputationRuleset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reputation/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * نبضة الزمن — النوافذ وتلاشي القديم وإعادة الحساب المستحقّة
         * @description تقرأ النبضة الاستحقاقات المخزّنة (`next_recompute_at`) والنوافذ المتحرّكة، فتُعيد حساب ما
         *     استحقّ وترفع إشارات القواعد التي تجاوزت عتباتها. لا `requestBody` هنا عمداً: النبضة فعلٌ
         *     على الساعة والحالة المخزّنة.
         *
         *     والفشل في شخصٍ واحد **يُعدّ ولا يُرمى**: النبضة عمليّة جماعية، ورفعُ خطأٍ لأجل صفٍّ واحد
         *     يُوقف بقيّة العمل ويُخفي الفشل عن العدّاد الذي يُراقَب.
         */
        post: operations["tickReputation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فحص جاهزية الخدمة
         * @description `memory` يجعل النتيجة `degraded` في التشغيل الحقيقي لأن إعادة التشغيل تُفقد الدفتر، وهو
         *     الأصل الذي لا يُعاد بناؤه من شيء. و`last_tick_at` مؤشّر غياب المُنادي الدوريّ: بلا نبضة
         *     تتقادم النتائج ولا تُرفَع إشارة ولا يشتكي أحد.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque؛ لا يُحلّل ولا يربط مباشرة بقاعدة هوية أخرى. */
        WaslaPublicId: string;
        /** @description مُعرّف الطلب كما يملكه محرّك الطلب؛ مرجع opaque بلا FK عابر للخدمات. */
        OrderPublicId: string;
        /**
         * @description من تُقاس سمعته. الطرفان لا طرفٌ واحد.
         * @enum {string}
         */
        SubjectType: "customer" | "driver";
        /**
         * @description قائمة مُقفلة، كل نوعٍ فيها له حدثٌ منشور يُنتجه اليوم. نوعٌ لا مصدر له لا يُضاف.
         * @enum {string}
         */
        FactKind: "order_completed" | "order_cancelled_by_customer" | "order_cancelled_by_driver" | "assignment_accepted" | "assignment_rejected" | "assignment_timed_out" | "rating_received";
        /**
         * @description بمفردات محرّك الطلب كما وصلت في الحدث. مرجعٌ لا حُكم.
         * @enum {string}
         */
        ActorType: "system" | "customer" | "driver" | "partner" | "admin";
        /**
         * @description رتبةٌ مُشتقّة من النتيجة وعتبات النسخة. تسميةٌ تُقرأ ولا تُنفَّذ (القرار 7).
         * @enum {string}
         */
        Tier: "new" | "standard" | "trusted" | "under_watch";
        /** @enum {string} */
        RecomputeTrigger: "fact_recorded" | "tick" | "manual_recompute";
        /**
         * @description قائمة مُقفلة تُحصى وتُقارَن، بخلاف نصٍّ حرّ يُقرأ ولا يُقاس.
         * @enum {string}
         */
        RatingReasonCode: "on_time" | "late_arrival" | "courteous" | "poor_conduct" | "unsafe_driving" | "vehicle_condition" | "route_deviation" | "no_show";
        /** @enum {string} */
        FraudRuleCode: "repeated_customer_cancellation" | "repeated_driver_cancellation" | "accept_then_abandon" | "offer_timeout_streak" | "rating_extremity_burst";
        /** @enum {string} */
        Severity: "low" | "medium" | "high";
        ReputationFact: {
            /** Format: uuid */
            id: string;
            subject_type: components["schemas"]["SubjectType"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            fact_kind: components["schemas"]["FactKind"];
            order_public_id: components["schemas"]["OrderPublicId"];
            source_event_type: string;
            /** Format: uuid */
            source_event_id: string;
            /** @description ترتيب الانتقال على الطلب كما جاء في الحدث؛ مفتاحُ عدم التكرار لا معلومةً زائدة. */
            source_sequence: number;
            actor_type: components["schemas"]["ActorType"];
            reason_code?: string | null;
            /**
             * Format: date-time
             * @description زمن الواقعة في العالم.
             */
            occurred_at: string;
            /**
             * Format: date-time
             * @description زمن تسجيلها عندنا. الفرقُ بينهما تأخّرُ الناقل، وخلطُهما يجعل النافذة المتحرّكة تكذب.
             */
            recorded_at: string;
        };
        ReputationFactList: {
            facts: components["schemas"]["ReputationFact"][];
        };
        FactRecordRequest: {
            subject_type: components["schemas"]["SubjectType"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            fact_kind: components["schemas"]["FactKind"];
            order_public_id: components["schemas"]["OrderPublicId"];
            source_event_type: string;
            /** Format: uuid */
            source_event_id: string;
            source_sequence: number;
            actor_type: components["schemas"]["ActorType"];
            reason_code?: string | null;
            /** Format: date-time */
            occurred_at: string;
        };
        FactRecordResult: {
            fact: components["schemas"]["ReputationFact"];
            score: components["schemas"]["ReputationScore"];
            /**
             * @description هل كانت الواقعة مسجّلةً من نفس المصدر؟ يُعاد صريحاً لأن المستهلك يحتاج أن يفرّق بين
             *     «سجّلتُ الآن» و«كانت مسجّلة» ليعدّ ما فعله، وبلا هذا الحقل يُفسَّر `200` تخميناً.
             */
            duplicate: boolean;
        };
        ReputationScore: {
            subject_type: components["schemas"]["SubjectType"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            /** @description نسخةُ القواعد التي أنتجت هذا الرقم؛ بلا هذا الحقل لا يُفسَّر رقمُ الأمس بعد تعديل الأوزان. */
            ruleset_version: number;
            score_points: number;
            tier: components["schemas"]["Tier"];
            fact_count: number;
            /** Format: uuid */
            computed_through_fact_id?: string | null;
            /** Format: date-time */
            computed_at: string;
            /**
             * Format: date-time
             * @description استحقاقُ إعادة الحساب — فهرسُ النبضة، لا مؤقّتٌ في الذاكرة يُنسى بإعادة التشغيل.
             */
            next_recompute_at: string;
        };
        ReputationRating: {
            /** Format: uuid */
            id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            rater_type: components["schemas"]["SubjectType"];
            rater_public_id: components["schemas"]["WaslaPublicId"];
            subject_type: components["schemas"]["SubjectType"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            stars: number;
            reason_code?: components["schemas"]["RatingReasonCode"] | null;
            ruleset_version: number;
            /** Format: date-time */
            submitted_at: string;
        };
        ReputationRatingList: {
            ratings: components["schemas"]["ReputationRating"][];
        };
        RatingSubmitRequest: {
            order_public_id: components["schemas"]["OrderPublicId"];
            rater_type: components["schemas"]["SubjectType"];
            rater_public_id: components["schemas"]["WaslaPublicId"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            stars: number;
            reason_code?: components["schemas"]["RatingReasonCode"] | null;
            /**
             * Format: date-time
             * @description زمن التقييم في العالم؛ يُقارَن بنافذة `rating_window_hours` من واقعة الاكتمال.
             */
            submitted_at?: string;
        };
        RatingSubmitResult: {
            rating: components["schemas"]["ReputationRating"];
            fact: components["schemas"]["ReputationFact"];
            score: components["schemas"]["ReputationScore"];
        };
        FraudSignal: {
            /** Format: uuid */
            id: string;
            subject_type: components["schemas"]["SubjectType"];
            subject_public_id: components["schemas"]["WaslaPublicId"];
            rule_code: components["schemas"]["FraudRuleCode"];
            severity: components["schemas"]["Severity"];
            observed_count: number;
            threshold_count: number;
            /** Format: date-time */
            window_started_at: string;
            /** Format: date-time */
            window_ended_at: string;
            ruleset_version: number;
            /** Format: date-time */
            raised_at: string;
        };
        FraudSignalList: {
            signals: components["schemas"]["FraudSignal"][];
        };
        ReputationRuleWeight: {
            subject_type: components["schemas"]["SubjectType"];
            fact_kind: components["schemas"]["FactKind"];
            /** @description قد يكون سالباً — الإلغاء يخصم. عددٌ صحيح لا عاشر، لأن النقاط تُجمَع وتُقارَن. */
            weight_points: number;
        };
        ReputationFraudThreshold: {
            rule_code: components["schemas"]["FraudRuleCode"];
            subject_type: components["schemas"]["SubjectType"];
            threshold_count: number;
            severity: components["schemas"]["Severity"];
        };
        ReputationRuleset: {
            ruleset_version: number;
            label: string;
            score_floor: number;
            score_ceiling: number;
            starting_score: number;
            min_facts_for_score: number;
            decay_half_life_days: number;
            tier_standard_at: number;
            tier_trusted_at: number;
            tier_under_watch_below: number;
            rating_window_hours: number;
            fraud_window_days: number;
            recompute_interval_hours: number;
            /** @description نسخةٌ غير مجمّدة لا تُستعمل في حساب (`REPUTATION_RULESET_NOT_FROZEN`)؛ أحكامٌ قابلة للتحرير تجعل تفسير نتيجة الأمس مستحيلاً. */
            is_frozen: boolean;
            weights: components["schemas"]["ReputationRuleWeight"][];
            fraud_thresholds: components["schemas"]["ReputationFraudThreshold"][];
        };
        ReputationRulesetList: {
            rulesets: components["schemas"]["ReputationRuleset"][];
        };
        TickResult: {
            /** Format: date-time */
            ran_at: string;
            scores_recomputed: number;
            tiers_changed: number;
            fraud_signals_raised: number;
            /**
             * @description يُعدّ ولا يُرمى: النبضة عمليّة جماعية، ورفعُ خطأٍ لأجل شخصٍ واحد يُوقف بقيّة العمل
             *     ويُخفي الفشل عن العدّاد الذي يُراقَب.
             */
            failures: number;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            persistence: "postgres" | "memory";
            /**
             * Format: date-time
             * @description آخر نبضة نُفّذت في هذه العمليّة، و`null` قبل أولاها.
             */
            last_tick_at: string | null;
        };
        ErrorResponse: {
            error: {
                /** @description كود ثابت؛ يتعاقد المستهلك على الكود لا على ترجمة الرسالة. */
                code: string;
                message: string;
                /**
                 * @description تفاصيل بنيوية بلا إعادة قيمة المدخل. الحقول **معدودة** لا حقيبة حرّة، وهي مُعلَنة
                 *     من المراجعة 1/6 لأن `additionalProperties: false` بلا `properties` تعني **لا مفتاح
                 *     مسموح**، فكل تفصيل كان سيُفشل تحقّق مستهلكٍ صارم على استجابةٍ صحيحة (درس Phase 05 · MR 4/6).
                 */
                details?: {
                    /** @description اسم الحقل المرفوض لا قيمته. */
                    field?: string;
                    /** @description وصف الشكل المتوقّع أو القاعدة المرفوضة. */
                    expected?: string;
                    subject_type?: components["schemas"]["SubjectType"];
                    fact_kind?: components["schemas"]["FactKind"];
                    ruleset_version?: number;
                    /** @description أحدثُ ترتيبٍ مسجَّل لهذا الطلب؛ يُعاد كي يعرف المُرسل أن حدثه متأخّر لا مرفوض. */
                    recorded_sequence?: number;
                    rating_window_hours?: number;
                    /**
                     * @description اسم قيد القاعدة الذي كان سيرفض الكتابة نفسها؛ يجعل خطّ الدفاع الثاني قابلاً
                     *     للعثور بدلاً من افتراض أن القاعدة تعيش في TypeScript وحدها.
                     */
                    constraint?: string;
                };
            };
            trace_id: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً أو `Idempotency-Key` مفقود أو مُرشِّح ناقص */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description النتيجة أو الواقعة أو نسخة القواعد غير موجودة */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض في إعادة استعمال مفتاح التفرّد أو في تقييمٍ مسجَّل أو نتيجةٍ تغيّرت أثناء الحساب */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخل صالح شكلياً ومرفوض بقاعدة أعمال أو نسخةِ قواعد أو حالةِ الطلب */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة أو الاستمرارية في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description العميل والسائق كلاهما تُقاس سمعته؛ المسار يُصرّح بالجانب كي لا يُخمَّن من شكل المُعرّف. */
        SubjectType: components["schemas"]["SubjectType"];
        SubjectPublicId: components["schemas"]["WaslaPublicId"];
        RulesetVersion: number;
        /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج واقعةً ثانية ولا نقطةً مضاعفة. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listReputationFacts: {
        parameters: {
            query?: {
                subjectPublicId?: components["schemas"]["WaslaPublicId"];
                subjectType?: components["schemas"]["SubjectType"];
                orderPublicId?: components["schemas"]["OrderPublicId"];
                factKind?: components["schemas"]["FactKind"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الوقائع المطابقة، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationFactList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    recordReputationFact: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج واقعةً ثانية ولا نقطةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactRecordRequest"];
            };
        };
        responses: {
            /** @description نفس المصدر أو نفس مفتاح التفرّد سُجّل سابقاً — تُعاد الواقعة نفسها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRecordResult"];
                };
            };
            /** @description سُجّلت الواقعة ومعها النتيجة بعد الحساب */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRecordResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getReputationScore: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description العميل والسائق كلاهما تُقاس سمعته؛ المسار يُصرّح بالجانب كي لا يُخمَّن من شكل المُعرّف. */
                subjectType: components["parameters"]["SubjectType"];
                subjectPublicId: components["parameters"]["SubjectPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description النتيجة والرتبة ومصدر الحساب */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationScore"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    recomputeReputationScore: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج واقعةً ثانية ولا نقطةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description العميل والسائق كلاهما تُقاس سمعته؛ المسار يُصرّح بالجانب كي لا يُخمَّن من شكل المُعرّف. */
                subjectType: components["parameters"]["SubjectType"];
                subjectPublicId: components["parameters"]["SubjectPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description أُعيد الحساب — وقد تكون النتيجة نفسها بلا تغيير */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationScore"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listReputationRatings: {
        parameters: {
            query?: {
                subjectPublicId?: components["schemas"]["WaslaPublicId"];
                orderPublicId?: components["schemas"]["OrderPublicId"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description التقييمات المطابقة، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRatingList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    submitReputationRating: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج واقعةً ثانية ولا نقطةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingSubmitRequest"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — يُعاد التقييم نفسه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSubmitResult"];
                };
            };
            /** @description سُجّل التقييم ومعه الواقعة التي أنتجها */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSubmitResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listFraudSignals: {
        parameters: {
            query?: {
                subjectPublicId?: components["schemas"]["WaslaPublicId"];
                subjectType?: components["schemas"]["SubjectType"];
                ruleCode?: components["schemas"]["FraudRuleCode"];
                severity?: components["schemas"]["Severity"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الإشارات المطابقة، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FraudSignalList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listReputationRulesets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description النسخ، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRulesetList"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getReputationRuleset: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                rulesetVersion: components["parameters"]["RulesetVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description النسخة وأوزانها وعتبات قواعد الاحتيال فيها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReputationRuleset"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    tickReputation: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج واقعةً ثانية ولا نقطةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description اكتملت النبضة، وقد تكون العدّادات صفراً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حالة الخدمة وطبقة الاستمرارية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
