/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a support ticket */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a ticket by ID */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets/{ticketId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach evidence to a ticket */
        post: operations["attachEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets/{ticketId}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate a ticket */
        post: operations["escalateTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets/{ticketId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a ticket */
        post: operations["resolveTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/tickets/{ticketId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a resolved ticket */
        post: operations["closeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @constant */
            service: "support-service";
            /** @constant */
            port: 8095;
        };
        Ticket: {
            /** Format: uuid */
            ticket_id: string;
            /** @enum {string} */
            ticket_type: "order_issue" | "behavior_complaint" | "payment_dispute" | "service_quality";
            /** @enum {string} */
            state: "open" | "investigating" | "escalated" | "resolved" | "closed";
            /** @enum {string|} */
            escalation_level: "support_agent" | "support_supervisor" | "admin" | null;
            reporter_public_id: string;
            subject_public_id: string | null;
            order_public_id: string | null;
            /** @enum {string|} */
            resolution_reason: "refund_issued" | "warning_sent" | "no_action_needed" | "escalated_to_admin" | null;
            /** Format: uuid */
            evidence_id: string | null;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            investigating_at: string | null;
            /** Format: date-time */
            escalated_at: string | null;
            /** Format: date-time */
            resolved_at: string | null;
            /** Format: date-time */
            closed_at: string | null;
        };
        Evidence: {
            /** Format: uuid */
            evidence_id: string;
            /** Format: uuid */
            ticket_id: string;
            /** @enum {string} */
            evidence_type: "photo" | "message" | "order_log";
            content_hash: string;
            storage_ref: string;
            /** Format: date-time */
            attached_at: string;
        };
        CreateTicketRequest: {
            /** @enum {string} */
            ticket_type: "order_issue" | "behavior_complaint" | "payment_dispute" | "service_quality";
            reporter_public_id: string;
            subject_public_id: string | null;
            order_public_id: string | null;
        };
        AttachEvidenceRequest: {
            /** @enum {string} */
            evidence_type: "photo" | "message" | "order_log";
            content_hash: string;
            storage_ref: string;
        };
        EscalateRequest: {
            /** @enum {string} */
            escalation_level: "support_agent" | "support_supervisor" | "admin";
        };
        ResolveRequest: {
            /** @enum {string} */
            resolution_reason: "refund_issued" | "warning_sent" | "no_action_needed" | "escalated_to_admin";
            /** Format: uuid */
            evidence_id: string;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @enum {string} */
                        code: "SUPPORT_VALIDATION_FAILED" | "SUPPORT_TICKET_NOT_FOUND" | "SUPPORT_EVIDENCE_REQUIRED" | "SUPPORT_RESOLUTION_REASON_REQUIRED" | "SUPPORT_INVALID_STATE_TRANSITION" | "SUPPORT_TICKET_ALREADY_CLOSED" | "SUPPORT_EVIDENCE_NOT_FOUND";
                        message: string;
                        trace_id?: string | null;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description Ticket created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    attachEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachEvidenceRequest"];
            };
        };
        responses: {
            /** @description Evidence attached */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    escalateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Ticket escalated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    resolveTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Ticket resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
    closeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
}
