/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/geo/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة البلدان */
        get: operations["listCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/countries/{countryId}/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مناطق/إمارات بلد */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/regions/{regionId}/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مدن منطقة */
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/cities/{cityId}/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** أحياء مدينة */
        get: operations["listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/districts/{districtId}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مناطق فرعية لحي */
        get: operations["listZones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** تفاصيل منطقة فرعية (مع المسار الكامل للوالدين) */
        get: operations["getZone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/users/{waslaPublicId}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** الموقع الحالي للمستخدم */
        get: operations["getUserLocation"];
        /** تعيين/تحديث موقع المستخدم */
        put: operations["setUserLocation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geo/users/{waslaPublicId}/location/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** سجل تغييرات موقع المستخدم */
        get: operations["getUserLocationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description اللغة المدعومة. ar = اللغة الافتراضية/الأساسية (fallback).
         * @enum {string}
         */
        Locale: "ar" | "en" | "ur";
        /** @enum {string} */
        GeoStatus: "active" | "inactive";
        /** @description الاسم بكل اللغات. ar إلزامي (fallback). */
        LocalizedName: {
            ar: string;
            en?: string | null;
            ur?: string | null;
        };
        Country: {
            /** Format: uuid */
            id: string;
            /** @description ISO 3166-1 alpha-2 (مثال: SA) */
            code: string;
            /** @description ISO 3166-1 alpha-3 (مثال: SAU) */
            iso3?: string;
            status: components["schemas"]["GeoStatus"];
            /** @description الاسم بالـlocale المطلوب */
            name: string;
        };
        Region: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            country_id: string;
            code: string;
            status: components["schemas"]["GeoStatus"];
            name: string;
        };
        City: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            region_id: string;
            code: string;
            status: components["schemas"]["GeoStatus"];
            name: string;
        };
        District: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            city_id: string;
            code: string;
            status: components["schemas"]["GeoStatus"];
            name: string;
        };
        Zone: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            district_id: string;
            code: string;
            status: components["schemas"]["GeoStatus"];
            name: string;
        };
        /** @description المنطقة مع مسار الهرم الكامل والاسم المترجم */
        ZoneDetail: {
            /** Format: uuid */
            id: string;
            code: string;
            status: components["schemas"]["GeoStatus"];
            name: string;
            path: {
                country: components["schemas"]["Country"];
                region: components["schemas"]["Region"];
                city: components["schemas"]["City"];
                district: components["schemas"]["District"];
            };
        };
        UserLocation: {
            wasla_public_id: string;
            zone: components["schemas"]["Zone"];
            /** @enum {string} */
            source: "customer_bot" | "driver_bot" | "partner_bot" | "admin" | "system";
            /** Format: date-time */
            effective_at: string;
            /** @description optimistic concurrency */
            version: number;
        };
        SetUserLocationRequest: {
            /** Format: uuid */
            zone_id: string;
            /** @enum {string} */
            source: "customer_bot" | "driver_bot" | "partner_bot" | "admin" | "system";
        };
        UserLocationHistoryEntry: {
            old_zone: {
                /** Format: uuid */
                id?: string;
                name?: string;
            } | null;
            new_zone: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            /** Format: date-time */
            changed_at: string;
            /** @enum {string} */
            source: "customer_bot" | "driver_bot" | "partner_bot" | "admin" | "system";
        };
        ErrorResponse: {
            /** @description كود ثابت (stable) */
            code: string;
            message: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الكيان غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض حالة */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخلات صالحة شكلياً لكن غير مقبولة منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
        Locale: components["schemas"]["Locale"];
        CountryId: string;
        RegionId: string;
        CityId: string;
        DistrictId: string;
        ZoneId: string;
        WaslaPublicId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCountries: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description قائمة البلدان بالاسم المترجم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Country"][];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listRegions: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                countryId: components["parameters"]["CountryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description قائمة المناطق */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"][];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listCities: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                regionId: components["parameters"]["RegionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description قائمة المدن */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"][];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDistricts: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                cityId: components["parameters"]["CityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description قائمة الأحياء */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["District"][];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listZones: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                districtId: components["parameters"]["DistrictId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description قائمة المناطق الفرعية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"][];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getZone: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المنطقة الفرعية مع مسار الهرم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getUserLocation: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الموقع الحالي للمستخدم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLocation"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    setUserLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUserLocationRequest"];
            };
        };
        responses: {
            /** @description تم تحديث الموقع (تغيير) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLocation"];
                };
            };
            /** @description تم تعيين الموقع لأول مرة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLocation"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getUserLocationHistory: {
        parameters: {
            query?: {
                /** @description اللغة المطلوبة للاسم (ar=en=ur). الافتراضي ar. */
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description سجل تغييرات الموقع */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLocationHistoryEntry"][];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
