/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customers/{waslaPublicId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ملف العميل */
        get: operations["getCustomerProfile"];
        /** إنشاء/تحديث ملف العميل (idempotent بطبيعته) */
        put: operations["upsertCustomerProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{waslaPublicId}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة الأماكن المحفوظة */
        get: operations["listSavedPlaces"];
        put?: never;
        /** إضافة مكان محفوظ */
        post: operations["createSavedPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{waslaPublicId}/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** حذف مكان محفوظ */
        delete: operations["deleteSavedPlace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{waslaPublicId}/order-requests/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * معاينة الطلب — تحقّق كامل بلا أي كتابة وبلا تسليم
         * @description نفس تحقّق الإنشاء بالضبط (نفس الأكواد)، لكن بلا صفّ في قاعدة البيانات وبلا نداء للمحرّك.
         *     المعاينة **لا تُقدّر سعراً ولا مسافة** (ADR-009 §6): تُعيد ما أدخله العميل مُطبَّعاً ومُسمّى.
         */
        post: operations["previewOrderRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{waslaPublicId}/order-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** طلبات العميل التي أنشأها من هذه الخدمة */
        get: operations["listOrderRequests"];
        put?: never;
        /**
         * إنشاء طلب وتسليمه إلى محرّك الطلبات
         * @description يُتحقّق من الطلب، يُسجَّل محلياً، ثم يُسلَّم إلى محرّك الطلبات عبر `OrderIntakePort`.
         *     إن تعذّر التسليم يبقى الطلب بحالة `submission_failed` ويُرجَع 503 — لا طلب صامت بلا مالك.
         */
        post: operations["createOrderRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{waslaPublicId}/order-requests/{orderRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** طلب واحد */
        get: operations["getOrderRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فحص الجاهزية */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description لغة العميل المفضّلة. ar = الافتراضية.
         * @enum {string}
         */
        Locale: "ar" | "en" | "ur";
        /**
         * @description نوع الطلب الذي يملكه العميل في هذه المرحلة. باقي الأنواع (Store/Partner) لمراحلها.
         * @enum {string}
         */
        OrderType: "ride" | "delivery";
        /**
         * @description قائمة مُقفلة (ADR-009 §7). Phase 05 تُعلن قدرات السائق بنفس المفردات،
         *     فالقيمة الحرّة تُنتج طلباً لا يطابقه أحد. إضافة نوع = تغيير عقد.
         * @enum {string}
         */
        VehicleClass: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
        /** @enum {string} */
        PriceMode: "customer_offer" | "negotiable";
        /** @enum {string} */
        StopKind: "pickup" | "dropoff";
        /**
         * @description من أين جاءت النقطة (§13). يُخزَّن كدليل تشغيلي ومدخل مستقبلي لعكس الترميز الجغرافي.
         * @enum {string}
         */
        StopSource: "map" | "telegram_location" | "link" | "text_search" | "saved_place" | "manual_zone";
        /**
         * @description حالات خدمة العميل فقط — **ليست حالات الطلب**. آلة حالة الطلب تملكها Phase 06 (§15).
         *     `submitted` = قبِله المحرّك · `submission_failed` = تعذّر التسليم ولم يُقبَل.
         * @enum {string}
         */
        OrderRequestStatus: "submitted" | "submission_failed";
        Money: {
            /** @description المبلغ بالوحدة الصغرى (هللات لـSAR) — لا عدد عشري في المال. */
            amount_minor: number;
            /** @description ISO 4217 (SAR في الإطلاق السعودي). */
            currency: string;
        };
        Coordinates: {
            latitude: number;
            longitude: number;
        };
        StopInput: {
            kind: components["schemas"]["StopKind"];
            /**
             * Format: uuid
             * @description مُعرّف منطقة فرعية من هرم الجغرافيا — يُتحقّق من وجوده ونشاطه.
             */
            zone_id: string;
            label?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            source: components["schemas"]["StopSource"];
            /**
             * Format: uuid
             * @description إن كان المصدر `saved_place` فهذا المكان الذي اشتُقّت منه النقطة.
             */
            saved_place_id?: string | null;
        };
        Stop: {
            kind: components["schemas"]["StopKind"];
            sequence: number;
            /** Format: uuid */
            zone_id: string;
            /** @description مسار المنطقة المقروء (مدينة/حي/منطقة فرعية) بلغة العميل — للعرض فقط. */
            zone_path?: string | null;
            label?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            source: components["schemas"]["StopSource"];
            /** Format: uuid */
            saved_place_id?: string | null;
        };
        CustomerProfile: {
            wasla_public_id: string;
            display_name?: string | null;
            preferred_locale: components["schemas"]["Locale"];
            /** Format: uuid */
            default_zone_id?: string | null;
            /** @enum {string} */
            status: "active" | "suspended";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description الحقول غير المُرسلة تبقى كما هي. `display_name` نصّ يكتبه المستخدم — لا يُشتَقّ من Telegram
         *     ولا يحمل رقم هاتف (§12.3: لا كشف بيانات حسّاسة).
         */
        UpsertCustomerProfileRequest: {
            display_name?: string | null;
            preferred_locale?: components["schemas"]["Locale"];
            /** Format: uuid */
            default_zone_id?: string | null;
        };
        SavedPlace: {
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: uuid */
            zone_id: string;
            zone_path?: string | null;
            address_text?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateSavedPlaceRequest: {
            label: string;
            /** Format: uuid */
            zone_id: string;
            address_text?: string | null;
            coordinates?: components["schemas"]["Coordinates"] | null;
        };
        OrderRequestInput: {
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            price_mode: components["schemas"]["PriceMode"];
            /** @description إلزامي مع `customer_offer`، ووجوده مع `negotiable` خطأ تحقّق. */
            offered_price?: components["schemas"]["Money"] | null;
            /** @description نقطة انطلاق واحدة ونقطة وصول واحدة بالضبط في هذه المرحلة (ADR-009 §5). */
            stops: components["schemas"]["StopInput"][];
            /** @description للتوصيل فقط — وجوده مع `ride` خطأ تحقّق. */
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
        };
        ShipmentDetails: {
            /** @enum {string|null} */
            shipment_type?: "parcel" | "documents" | "food" | "goods" | "other" | null;
            description?: string | null;
            weight_kg?: number | null;
        };
        OrderRequestPreview: {
            /** @constant */
            valid: true;
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            price_mode: components["schemas"]["PriceMode"];
            offered_price?: components["schemas"]["Money"] | null;
            stops: components["schemas"]["Stop"][];
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
            /**
             * @description تنبيهات لا تمنع الإنشاء: انطلاق ووصول في نفس المنطقة الفرعية · طلب بلا سعر مقترح
             *     (مسار أساسي يفتح التفاوض — §12.1، وليس خطأ).
             */
            warnings?: ("same_zone_pickup_and_dropoff" | "no_price_offered")[];
        };
        OrderRequest: {
            /**
             * Format: uuid
             * @description مُعرّف الطلب داخل خدمة العميل — **ليس** المعرّف العام للطلب.
             */
            id: string;
            wasla_public_id: string;
            /** @description يملكه محرّك الطلبات (Phase 06)؛ NULL حتى يُقبَل التسليم (ADR-009 §3). */
            order_public_id?: string | null;
            status: components["schemas"]["OrderRequestStatus"];
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            price_mode: components["schemas"]["PriceMode"];
            offered_price?: components["schemas"]["Money"] | null;
            stops: components["schemas"]["Stop"][];
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description الحمولة التي تُسلَّم إلى محرّك الطلبات عبر `OrderIntakePort` (ADR-009 §3).
         *     هذا **عقد التسليم**: بوابة خروج Phase 04 تتحقّق أن ما يستقبله المحرّك يطابقه،
         *     و Phase 06 تُنفّذ مُهيّئ HTTP يقرأه كما هو.
         */
        OrderIntakeRequest: {
            /** Format: uuid */
            order_request_id: string;
            customer_public_id: string;
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            price_mode: components["schemas"]["PriceMode"];
            offered_price?: components["schemas"]["Money"] | null;
            stops: components["schemas"]["Stop"][];
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
            /** Format: date-time */
            requested_at: string;
            idempotency_key?: string;
        };
        OrderIntakeResult: {
            /** @description يملكه المحرّك — خدمة العميل تُخزّنه ولا تُولّده. */
            order_public_id: string;
            /** Format: date-time */
            accepted_at: string;
        };
        ErrorResponse: {
            /** @description كود ثابت (stable) */
            code: string;
            message: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الكيان غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض حالة */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخلات صالحة شكلياً لكن غير مقبولة منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة أو تابعٌ لها في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        WaslaPublicId: string;
        PlaceId: string;
        OrderRequestId: string;
        /** @description مفتاح تفرّد من العميل (§43). تكراره يُعيد نفس الكيان بـ200 ولا يُنشئ ثانياً. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ملف العميل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    upsertCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertCustomerProfileRequest"];
            };
        };
        responses: {
            /** @description حُدّث ملف قائم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            /** @description أُنشئ ملف جديد */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listSavedPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الأماكن المحفوظة مرتّبة بالأحدث استعمالاً ثم بالإنشاء */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SavedPlace"][];
                        /** @description الحد الأقصى المسموح لهذا العميل */
                        limit: number;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createSavedPlace: {
        parameters: {
            query?: never;
            header: {
                /** @description مفتاح تفرّد من العميل (§43). تكراره يُعيد نفس الكيان بـ200 ولا يُنشئ ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSavedPlaceRequest"];
            };
        };
        responses: {
            /** @description نفس Idempotency-Key سُجّل سابقاً — يُعاد المكان نفسه بلا إنشاء ثانٍ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlace"];
                };
            };
            /** @description أُضيف المكان */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPlace"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteSavedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
                placeId: components["parameters"]["PlaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حُذف المكان (أو كان محذوفاً — العملية idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    previewOrderRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestInput"];
            };
        };
        responses: {
            /** @description الطلب صالح — هذه صورته قبل الإنشاء */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRequestPreview"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listOrderRequests: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الطلبات مرتّبة بالأحدث */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderRequest"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createOrderRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description مفتاح تفرّد من العميل (§43). تكراره يُعيد نفس الكيان بـ200 ولا يُنشئ ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequestInput"];
            };
        };
        responses: {
            /** @description نفس Idempotency-Key سُجّل سابقاً — يُعاد الطلب نفسه بلا تسليم ثانٍ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRequest"];
                };
            };
            /** @description أُنشئ الطلب وسُلّم إلى المحرّك */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRequest"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getOrderRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
                orderRequestId: components["parameters"]["OrderRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الطلب */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRequest"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخدمة تعمل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        /** @constant */
                        service: "customers-service";
                        /** @enum {string} */
                        persistence?: "postgres" | "memory";
                        /** @enum {string} */
                        order_intake?: "configured" | "unconfigured";
                    };
                };
            };
        };
    };
}
