/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * حالة الخدمة وآخر نبضة
         * @description `last_tick_at` معلومة تشغيلية لا وعد منتجي: غيابها أو قدمها يعني أن الاستحقاقات المكتوبة
         *     في القاعدة لن يتقدمها أحد. إعلان ذلك أفضل من مؤقت مخفي يعمل في نسخة ويصمت في أخرى
         *     (ADR-011 القرار 3). لا يستنتج منها المستهلك أهلية سائق أو حالة طلب.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إنشاء مهمة توزيع صريحة لطلب
         * @description ينشئ مهمة في `pending` ثم تفتحها نبضة لاحقة؛ لا يستقصي التوزيع جدول الطلبات ولا ينشئ
         *     المهمة من حدث غير مستهلك بعد. عند الإنشاء يثبت نسخة القواعد وأحجام الأمواج ومهلها على
         *     المهمة، فلا يغير تعديل إعداد لاحق عرضاً جارياً (ADR-011 القرار 4).
         *
         *     - `201` مهمة جديدة.
         *     - `200` إعادة المفتاح نفسه والحمولة نفسها: المهمة واللقطة نفسيهما بلا حدث ثانٍ.
         *     - `400` جسم أو رأس لا يطابق العقد.
         *     - `409` المفتاح استعمل مع حمولة مختلفة، أو للطلب مهمة قائمة لا يجوز تكرارها.
         *     - `422` حمولة مفهومة لكن لا يمكن بدء توزيعها منطقياً.
         *     - `503` التوزيع أو منفذه الإلزامي غير متاح؛ لا يخمّن التوزيع بدلاً عن `orders` أو `matching`.
         */
        post: operations["createDispatchJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة مهمة توزيع
         * @description يعيد حالة التنسيق ولقطة الإعداد ومواعيدها؛ لا يعيد قرار المطابقة أو ملف السائق، لأنهما
         *     حدّان يملكان بياناتهما. `expires_at` يشرح متى تنتهي النافذة الآلية، و`escalation_expires_at`
         *     يشرح متى ينتهي المسار البشري إن صُعّد.
         */
        get: operations["getDispatchJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/jobs/{job_id}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة عروض مهمة توزيع مرتبة بالموجة ثم وقت العرض
         * @description يعيد سجل العروض لتدقيق قرار التوزيع، لا قائمة المرشحين ودرجاتهم: قرار المطابقة الحساس
         *     يبقى في `matching_decisions` ولا يدخل هذا الحد (ADR-011 القرار 8).
         */
        get: operations["listDispatchOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تقديم كل عرض وموجة وتصعيد استحق حتى الآن
         * @description بلا جسم عمداً: «الآن» يأتي من ساعة الخدمة المحقونة، لا من عميل يستطيع تزوير الزمن.
         *     تنهي النبضة العروض المنتهية، وتفتح الموجة التالية، ثم تسجل التصعيد أو الاستنفاد حيث يلزم.
         *     وهي idempotent: تكرارها لا يعيد إنهاء عرض أو فتح موجة لأن الانتقال الأول غيّر حالته.
         *
         *     - `200` نُفذت النبضة ويصف الملخص ما تحرك في هذا النداء، ولو كانت الأعداد صفراً.
         *     - `400` رأس idempotency أو رأس طلب غير صالح.
         *     - `503` منفذ `orders` أو `matching` أو التخزين غير متاح؛ يبقى الاستحقاق مكتوباً ليُعاد بنفس
         *       المفتاح بدلاً من أن يتحول إلى مؤقت ضائع.
         */
        post: operations["tickDispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/offers/{offer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة عرض توزيع واحد مع سياق وظيفته
         * @description يمكّن خدمة التفاوض من التحقق من العرض قبل فتح خيط. `standing` حقيقة مجال
         *     محسوبة من حالة العرض وحالة المهمة فقط: يكون صحيحاً عندما يظل العرض `offered`
         *     ولا تكون المهمة نهائية. لا نقارن `expires_at` بساعة الحائط هنا؛ الزمن في
         *     التوزيع نبضة لا مؤقت، ولذلك العرض الذي تجاوز موعده ولم تمر عليه نبضة يبقى
         *     قائماً إلى أن تسجل النبضة حسمه.
         *
         *     القراءة لا تحمل `Idempotency-Key` ولا تفتح معاملة كتابة: لا تغيّر حالة عرض
         *     ولا تقدّم مهلة، بل تقرأ القرار المسجل فقط.
         *
         *     - `200` العرض مع مراجع الطلب وحالة المهمة و`standing`.
         *     - `400` معامل أو رأس طلب لا يطابق العقد.
         *     - `404` لا عرض بهذا المعرّف.
         *     - `503` التخزين غير متاح.
         */
        get: operations["getDispatchOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/offers/{offer_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قبول عرض توزيع
         * @description القبول الأول فقط يفوز. يسجل التوزيع الحسم في `orders` عبر مفتاح حتمي مشتق من
         *     `(offer_id, action)`، ثم يلغي بقية عروض الموجة بسبب `OFFER_SUPERSEDED`. لا يستبدل التوزيع
         *     حكم محرك الطلبات: رفضه النهائي `409` أو `422` يبقى رفضاً مسجلاً.
         *
         *     - `200` قُبل العرض، أو أُعيدت نتيجة القبول نفسها بالمفتاح نفسه.
         *     - `400` رأس غير صالح.
         *     - `404` لا عرض بهذا المعرّف.
         *     - `409` العرض حُسم سابقاً أو فاز عرض آخر أو استعمل المفتاح مع حمولة مختلفة.
         *     - `422` الحسم مفهوم لكنه مرفوض نهائياً من محرّك الطلبات.
         *     - `503` الحسم غير مكتمل بسبب عطل قابل للإعادة؛ لا يتحول إلى رفض سائق.
         */
        post: operations["acceptDispatchOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/offers/{offer_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * رفض عرض توزيع بسبب من الكتالوج
         * @description لا يقبل نصاً حراً لأن سبب الرفض حدث وتحليل وتدقيق. يسجل التوزيع الرفض في `orders` ثم تفتح
         *     النبضة التالية المسار اللاحق إن استحق؛ الرفض ليس نهاية للطلب (ADR-010).
         *
         *     - `200` سجل الرفض بالكود المعلن، أو أعاد النتيجة نفسها بالمفتاح نفسه.
         *     - `400` الجسم أو الرأس لا يطابق العقد.
         *     - `404` لا عرض بهذا المعرّف.
         *     - `409` العرض حُسم سابقاً أو المفتاح استعمل بحمولة أخرى.
         *     - `422` الرفض مفهوم لكن محرك الطلبات رفض حسمه نهائياً.
         *     - `503` عطل قابل للإعادة؛ السبب لا يبدل إلى «غير متاح».
         */
        post: operations["rejectDispatchOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إلغاء مهمة توزيع بسبب من الكتالوج
         * @description يوقف التنسيق فقط ولا يخترع انتقالاً للطلب: من يملك إلغاء الطلب يستدعي محرّكه وفق حدّه.
         *     تُلغى العروض المفتوحة بسبب `JOB_CANCELLED`، ويظل سبب المهمة المعلن قابلاً للتدقيق.
         *
         *     - `200` ألغيت المهمة، أو أُعيدت النتيجة نفسها بالمفتاح نفسه.
         *     - `400` الجسم أو الرأس لا يطابق العقد.
         *     - `404` لا مهمة بهذا المعرّف.
         *     - `409` المهمة نهائية أو المفتاح استعمل بحمولة أخرى.
         *     - `422` سبب الإلغاء ليس من الكتالوج أو لا يقبل من الحالة الحالية.
         *     - `503` التخزين أو منفذ الحسم الإلزامي غير متاح.
         */
        post: operations["cancelDispatchJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque. لا يُحلّل ولا يثبت وجود ملف سائق. */
        WaslaPublicId: string;
        /** @description مُعرّف طلب عام opaque تملكه خدمة orders. */
        OrderPublicId: string;
        /** @description كود من [errors.md](errors.md)، لا نص حر ولا رسالة واجهة. */
        ReasonCode: string;
        /** @enum {string} */
        DispatchJobStatus: "pending" | "dispatching" | "escalated_community" | "assigned" | "exhausted" | "cancelled";
        /** @enum {string} */
        DispatchWaveStatus: "open" | "completed" | "cancelled";
        /** @enum {string} */
        DispatchOfferStatus: "offered" | "accepted" | "rejected" | "timed_out" | "superseded" | "cancelled";
        /** @enum {string} */
        OrderType: "ride" | "delivery";
        /** @enum {string} */
        VehicleClass: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
        CreateDispatchJobRequest: {
            /**
             * Format: uuid
             * @description مرجع UUID opaque لطلب تملكه خدمة أخرى؛ لا FK عبر حدود الخدمات.
             */
            order_id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            /**
             * Format: uuid
             * @description مستوى المنطقة للمطابقة؛ لا إحداثيات أو عنوان حر.
             */
            zone_id: string;
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
        };
        /** @description لقطة مثبتة عند الإنشاء؛ ليست معرف إعداد يُعاد حله لاحقاً. */
        DispatchRulesSnapshot: {
            ruleset_version: number;
            wave_size: number;
            offer_timeout_seconds: number;
            max_waves: number;
            escalation_timeout_seconds: number;
        };
        DispatchJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            /** Format: uuid */
            zone_id: string;
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            status: components["schemas"]["DispatchJobStatus"];
            status_reason_code?: components["schemas"]["ReasonCode"] | null;
            rules: components["schemas"]["DispatchRulesSnapshot"];
            /**
             * Format: date-time
             * @description نهاية النافذة الآلية المحفوظة؛ النبضة فقط تقدمها.
             */
            expires_at: string;
            /**
             * Format: date-time
             * @description نهاية التصعيد المحفوظة، حتى لا تبقى مهمة بشرية بلا نهاية.
             */
            escalation_expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DispatchOffer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            wave_id: string;
            driver_public_id: components["schemas"]["WaslaPublicId"];
            status: components["schemas"]["DispatchOfferStatus"];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Format: date-time */
            offered_at: string;
            /** Format: date-time */
            expires_at: string;
            responded_at?: string | null;
            resolved_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DispatchOfferDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            wave_id: string;
            driver_public_id: components["schemas"]["WaslaPublicId"];
            status: components["schemas"]["DispatchOfferStatus"];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Format: date-time */
            offered_at: string;
            /** Format: date-time */
            expires_at: string;
            responded_at?: string | null;
            resolved_at?: string | null;
            /** Format: date-time */
            created_at: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            /** Format: uuid */
            order_id: string;
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            job_status: components["schemas"]["DispatchJobStatus"];
            /** @description صحيح ما دام العرض offered والمهمة غير نهائية؛ لا يقارن expires_at بساعة الحائط، لأن النبضة وحدها تقدّم المهل. */
            standing: boolean;
        };
        DispatchOfferList: {
            items: components["schemas"]["DispatchOffer"][];
        };
        RejectOfferRequest: {
            /**
             * @description كود رفض مُغلق؛ لا نمرر سبباً كتبه السائق إلى الحدث أو التحليل.
             * @enum {string}
             */
            reason_code: "DRIVER_DECLINED" | "DRIVER_UNAVAILABLE" | "DRIVER_VEHICLE_ISSUE";
        };
        CancelDispatchJobRequest: {
            /** @enum {string} */
            reason_code: "ORDER_CANCELLED" | "DISPATCH_CANCELLED_BY_REQUESTER" | "ORDER_ENGINE_REJECTED";
        };
        TickResult: {
            /**
             * Format: date-time
             * @description الساعة المحقونة التي قورنت بها الاستحقاقات، لا وقتاً أرسله العميل.
             */
            tick_at: string;
            timed_out_offers: number;
            opened_waves: number;
            escalated_jobs: number;
            exhausted_jobs: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @constant */
            service: "dispatch-service";
            /** @enum {string} */
            persistence: "postgres" | "memory";
            /** @description آخر نبضة مكتملة؛ null يعني أن لا نبضة نجحت منذ بدء القياس. */
            last_tick_at: string | null;
        };
        ErrorResponse: {
            /** @description كود ثابت؛ الاختبارات والبرامج تتحقق منه لا من النص. */
            code: string;
            message: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description المهمة أو العرض غير موجود. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض حالة أو إعادة مفتاح بحمولة مختلفة أو تكرار قرار حُسم. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description حمولة صحيحة شكلياً لكنها غير مقبولة منطقياً أو رُفضت نهائياً من محرك الطلبات. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تخزين أو منفذ إلزامي غير متاح؛ إعادة المحاولة بالمفتاح نفسه آمنة. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobId: string;
        OfferId: string;
        /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخدمة أجابت بحالتها التشغيلية؛ قد تكون `degraded` كي يظهر العطل بدلاً من إخفائه. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createDispatchJob: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDispatchJobRequest"];
            };
        };
        responses: {
            /** @description إعادة idempotency بالمفتاح والحمولة نفسيهما — النتيجة الأصلية نفسها. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchJob"];
                };
            };
            /** @description أُنشئت مهمة جديدة تنتظر نبضة. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchJob"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDispatchJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المهمة الموجودة. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchJob"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    listDispatchOffers: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description العروض المعروفة للمهمة؛ القائمة الفارغة تعني أن النبضة لم تفتح موجة بعد أو لم تجد مرشحاً. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchOfferList"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    tickDispatch: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description اكتملت النبضة بلا أثر مضاعف، والملخص يبيّن القرارات التي حُسمت الآن. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDispatchOffer: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                offer_id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description العرض الموجود وسياق مهمته الذي يحتاجه مستهلك التفاوض. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchOfferDetail"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    acceptDispatchOffer: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                offer_id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description العرض المقبول وحالته النهائية. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchOffer"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    rejectDispatchOffer: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                offer_id: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectOfferRequest"];
            };
        };
        responses: {
            /** @description العرض المرفوض وحالة الرفض النهائية. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchOffer"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    cancelDispatchJob: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). إعادة المحاولة حقيقة شبكية لا خطأ استثنائي. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في مغلف الحدث وسجل التشغيل، لا معرّف قناة. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelDispatchJobRequest"];
            };
        };
        responses: {
            /** @description المهمة الملغاة وحالتها النهائية. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchJob"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
