/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/negotiations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قائمة خيوط التفاوض بمُرشِّح
         * @description مُرشِّح واحد على الأقل مطلوب (`orderPublicId` أو `driverPublicId`): قائمةٌ بلا مُرشِّح تعني
         *     قراءة محادثات كل الناس، وهي عمليّة لا يحتاجها أي مستهلك معلوم في هذه المرحلة.
         */
        get: operations["listNegotiationThreads"];
        put?: never;
        /**
         * فتح خيط تفاوض على عرض توزيع قائم
         * @description يُفتح الخيط بمبلغٍ ابتدائي هو **الدور رقم 1** بالضرورة: خيطٌ يُفتح فارغاً ثم يُنتظر فيه عرضٌ
         *     أوّل يجعل حالةً وسطى («مفتوح ولا شيء فيه») يجب أن يُفكّر فيها كل قارئ لاحقاً بلا مقابل.
         *     تكرار `Idempotency-Key` بالحمولة نفسها يعيد الخيط نفسه بـ`200`؛ إعادة الإرسال بعد انقطاع
         *     الشبكة حالة عادية لا سبب لخيطين.
         */
        post: operations["openNegotiationThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة خيط */
        get: operations["getNegotiationThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إغلاق الخيط من الخارج (سحب الطلب أو إلغاء العرض)
         * @description فعلٌ للتوزيع أو محرّك الطلب لا للطرفين: انسحابُ العميل من التفاوض **رفضٌ** له سببه
         *     (`declined_by_customer`) ويُعبَّر عنه بـ`reject`، أمّا `cancel` فيقول «زال سبب التفاوض
         *     أصلاً». خلطُ الاثنين يُخفي من أنهى الحديث.
         */
        post: operations["cancelNegotiationThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** أدوار الخيط بالترتيب */
        get: operations["listNegotiationRounds"];
        put?: never;
        /**
         * عرضٌ مضادّ — دورٌ جديد يُبطل ما قبله
         * @description العرض المضادّ يُنشئ الدور التالي ويجعل السابق `superseded` في المعاملة نفسها: تركُ
         *     دورَين معلّقَين يسمح بقبولَين لمبلغَين. و`expected_round_no` إلزامي لأن الطرف الذي
         *     يُرسل مقابلاً بناءً على شاشة قديمة يجب أن يُرفَض لا أن يُقحم مبلغه في سياقٍ تغيّر.
         */
        post: operations["proposeNegotiationRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/rounds/{roundNo}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قبول دور — هنا يقع الاتفاق
         * @description القبول ينشئ `Agreement` ويُغلق الخيط بـ`agreed` في معاملة واحدة، ثمّ يحاول تسليم السعر إلى
         *     محرّك الطلب. **فشل التسليم لا يُبطل الاتفاق** ولا يُغيّر رمز هذه الاستجابة (القرار 2):
         *     تُقرأ حالته من `handoff_state`، فيرى المستهلك «اتُّفق ولم يُسجَّل بعد» بدل أن يظنّ أنّ
         *     القبول لم يقع.
         */
        post: operations["acceptNegotiationRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/rounds/{roundNo}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * رفض دور — إمّا انتهاءُ الحديث وإمّا انتظارُ مقابل
         * @description `close_thread: true` يُنهي التفاوض بسبب الرافض؛ و`false` يُبقيه مفتوحاً بلا دورٍ معلّق حتى
         *     يأتي مقابل. الفرق مُعلَن في الحمولة لا مُستنتَج من الحالة، لأن «رفضتُ وسأقترح غيره» و
         *     «رفضتُ وانتهى» نيّتان لا يجوز أن يُخمّنهما الخادم.
         */
        post: operations["rejectNegotiationRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * رسائل الخيط بالتسلسل
         * @description الرسالة المحجوبة تُعاد بلا نصّ ومعها `redacted_at` وسببها: حذفُها من القائمة يجعل ثغرةً
         *     في التسلسل تُفسَّر خطأً بأنّها خطأ نظام.
         */
        get: operations["listNegotiationMessages"];
        put?: never;
        /**
         * إرسال رسالة في الخيط
         * @description الرسالة لا تُغيّر مبلغاً ولا حالة: سعرٌ مكتوب في نصّ ليس عرضاً، والعرض `POST /rounds`.
         *     وذلك مقصود — لو قرأ الخادم الأرقام من النصّ لصار الاتفاق تخميناً لُغوياً.
         */
        post: operations["postNegotiationMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/{threadId}/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة اتفاق الخيط وحالة تسليمه */
        get: operations["getNegotiationAgreement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/negotiations/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * نبضة الزمن — انتهاء الأدوار والخيوط وإعادة تسليم السعر
         * @description تقرأ النبضة الاستحقاقات المخزّنة (`next_tick_at` للخيوط و`next_handoff_at` للاتفاقات)
         *     وتُنهي ما استحقّ وتعيد محاولة ما لم يُسلَّم. لا `requestBody` هنا عمداً: النبضة فعلٌ على
         *     الساعة والحالة المخزّنة، وإعلان جسمٍ فارغ يجعل Fastify يرفض طلباً صحيحاً بـ`400`.
         */
        post: operations["tickNegotiations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فحص جاهزية الخدمة
         * @description `memory` يجعل النتيجة `degraded` في التشغيل الحقيقي لأن إعادة التشغيل تُفقد المحادثة
         *     والاتفاق، وهما دليلٌ يُسأل عنه لاحقاً. و`last_tick_at` مؤشّر غياب المُنادي الدوريّ
         *     (Phase 09): بلا نبضة تبقى الأدوار معلّقة إلى الأبد ولا يشتكي أحد.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque؛ لا يُحلّل ولا يربط مباشرة بقاعدة هوية أخرى. */
        WaslaPublicId: string;
        /** @description مُعرّف الطلب كما يملكه محرّك الطلب؛ مرجع opaque بلا FK عابر للخدمات. */
        OrderPublicId: string;
        /**
         * @description طرفا التفاوض. لا `system` هنا — النظام لا يعرض سعراً ولا يقبله.
         * @enum {string}
         */
        Party: "customer" | "driver";
        /**
         * Format: int64
         * @description مبلغ بالوحدة الصغرى للعملة (هللة للريال). عددٌ صحيح لا كسر عائم، لأن التفاوض يُساوي المبالغ.
         */
        AmountMinor: number;
        /** @description رمز العملة بثلاثة أحرف. صريحٌ في كل مبلغ كي لا يُفترَض من مكان التشغيل. */
        Currency: string;
        /** @enum {string} */
        ThreadState: "open" | "agreed" | "declined" | "expired" | "cancelled";
        /**
         * @description لا إغلاق بلا سبب مُعدَّد. الأكواد تُقارَن وتُحصى؛ الرسائل تُترجَم وتتغيّر.
         * @enum {string}
         */
        ThreadCloseReasonCode: "agreed" | "declined_by_customer" | "declined_by_driver" | "max_rounds_reached" | "thread_expired" | "cancelled_by_dispatch" | "order_withdrawn";
        /** @enum {string} */
        RoundState: "pending" | "accepted" | "rejected" | "superseded" | "expired";
        /**
         * @description حالة تسليم السعر إلى محرّك الطلب. `rejected` نهائية لا تُعاد: المحرّك قال «لا يقبل هذا
         *     الطلب سعراً الآن»، وإعادة السؤال إزعاجٌ لا إصلاح. و`abandoned` نفاد المحاولات.
         * @enum {string}
         */
        HandoffState: "pending" | "handed_off" | "rejected" | "abandoned";
        /** @enum {string} */
        Locale: "ar" | "en" | "ur";
        NegotiationThread: {
            /** Format: uuid */
            id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            customer_public_id: components["schemas"]["WaslaPublicId"];
            driver_public_id: components["schemas"]["WaslaPublicId"];
            /**
             * Format: uuid
             * @description مرجع opaque إلى عرض التوزيع الذي شرّع هذا التفاوض؛ وجوده يقرّره منفذ التوزيع لا FK.
             */
            dispatch_offer_id: string;
            /** @enum {string} */
            service_kind: "ride" | "delivery";
            state: components["schemas"]["ThreadState"];
            close_reason_code?: components["schemas"]["ThreadCloseReasonCode"] | null;
            policy_version: number;
            currency: components["schemas"]["Currency"];
            opening_amount_minor: components["schemas"]["AmountMinor"];
            opened_by: components["schemas"]["Party"];
            round_count: number;
            current_round_no: number;
            agreed_round_no?: number | null;
            /** Format: date-time */
            expires_at: string;
            /**
             * Format: date-time
             * @description أقرب استحقاق يعني هذا الخيط. `null` بعد الإغلاق — لا شيء ينتظر خيطاً منتهياً.
             */
            next_tick_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description تفاؤل الكتابة. يُعاد كي يستطيع المستهلك أن يكشف تغيّراً بين قراءته وفعله. */
            version?: number;
        };
        NegotiationThreadList: {
            threads: components["schemas"]["NegotiationThread"][];
        };
        ThreadOpenRequest: {
            order_public_id: components["schemas"]["OrderPublicId"];
            customer_public_id: components["schemas"]["WaslaPublicId"];
            driver_public_id: components["schemas"]["WaslaPublicId"];
            /** Format: uuid */
            dispatch_offer_id: string;
            /** @enum {string} */
            service_kind: "ride" | "delivery";
            opening_amount_minor: components["schemas"]["AmountMinor"];
            currency: components["schemas"]["Currency"];
            opened_by: components["schemas"]["Party"];
            /** @description رسالة تصاحب العرض الأول. تُخزَّن كرسالةٍ عادية ولا تدخل أي حدث. */
            opening_note?: string | null;
            source_locale?: components["schemas"]["Locale"];
        };
        ThreadCancelRequest: {
            /**
             * @description سببان فقط؛ انسحاب طرفٍ ليس إلغاءً بل رفض، ولذلك مسارٌ آخر.
             * @enum {string}
             */
            reason_code: "cancelled_by_dispatch" | "order_withdrawn";
        };
        NegotiationRound: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            thread_id: string;
            round_no: number;
            proposed_by: components["schemas"]["Party"];
            amount_minor: components["schemas"]["AmountMinor"];
            currency: components["schemas"]["Currency"];
            state: components["schemas"]["RoundState"];
            resolved_by?: components["schemas"]["Party"] | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            responded_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        NegotiationRoundList: {
            rounds: components["schemas"]["NegotiationRound"][];
        };
        RoundProposal: {
            proposed_by: components["schemas"]["Party"];
            amount_minor: components["schemas"]["AmountMinor"];
            currency: components["schemas"]["Currency"];
            /**
             * @description رقم آخر دور رآه المُرسل. عدم مطابقته للحالة الحقيقية يُرفض بـ`NEGOTIATION_ROUND_STALE`:
             *     مقابلٌ يُبنى على شاشة قديمة يجب أن يُرفض لا أن يُقحم في سياقٍ تغيّر.
             */
            expected_round_no: number;
            /** @description رسالة تصاحب العرض المضادّ؛ تُخزَّن رسالةً ولا تدخل أي حدث. */
            note?: string | null;
            source_locale?: components["schemas"]["Locale"];
        };
        RoundDecision: {
            acting_party: components["schemas"]["Party"];
            note?: string | null;
            source_locale?: components["schemas"]["Locale"];
        };
        RoundRejection: {
            acting_party: components["schemas"]["Party"];
            /** @description نيّةٌ مُعلَنة لا مُستنتَجة؛ «رفضتُ وسأقترح غيره» و«رفضتُ وانتهى» لا يخمّنهما الخادم. */
            close_thread: boolean;
            note?: string | null;
            source_locale?: components["schemas"]["Locale"];
        };
        NegotiationMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            thread_id: string;
            sequence_no: number;
            /** @enum {string} */
            author_role: "customer" | "driver" | "system";
            /** @description نصّ كتبه المستخدم. `null` على رسالة النظام وعلى المحجوب. */
            body?: string | null;
            /** @description رمز رسالة النظام بدل نصٍّ مترجم مخزّن؛ الرمز يُعرَض بأي لغة. */
            system_code?: string | null;
            round_no?: number | null;
            source_locale: components["schemas"]["Locale"];
            /** Format: date-time */
            redacted_at?: string | null;
            redaction_reason_code?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        NegotiationMessageList: {
            messages: components["schemas"]["NegotiationMessage"][];
        };
        MessageSubmission: {
            author_role: components["schemas"]["Party"];
            body: string;
            round_no?: number | null;
            source_locale?: components["schemas"]["Locale"];
        };
        NegotiationAgreement: {
            /** Format: uuid */
            thread_id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            driver_public_id: components["schemas"]["WaslaPublicId"];
            round_no: number;
            amount_minor: components["schemas"]["AmountMinor"];
            currency: components["schemas"]["Currency"];
            accepted_by: components["schemas"]["Party"];
            policy_version: number;
            /** Format: date-time */
            agreed_at: string;
            handoff_state: components["schemas"]["HandoffState"];
            handoff_attempts: number;
            /** Format: date-time */
            handed_off_at?: string | null;
            /** Format: date-time */
            next_handoff_at?: string | null;
            last_error_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TickResult: {
            /** Format: date-time */
            ticked_at: string;
            rounds_expired: number;
            threads_expired: number;
            /** @description خيوط أُغلقت لأن آخر دورٍ فيها انتهى وقد استُنفد سقف الأدوار — لا مجال لمقابلٍ آخر. */
            threads_closed_max_rounds: number;
            handoffs_attempted: number;
            handoffs_succeeded: number;
            /**
             * @description فشل التسليم يُعدّ ولا يُرمى: النبضة عمليّة جماعية، ورفعُ خطأٍ لأجل اتفاق واحد
             *     يُوقف بقيّة العمل ويُخفي الفشل عن العدّاد الذي يُراقَب.
             */
            handoff_failures: number;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            persistence: "postgres" | "memory";
            /**
             * Format: date-time
             * @description آخر نبضة نُفّذت في هذه العمليّة، و`null` قبل أولاها.
             */
            last_tick_at: string | null;
        };
        ErrorResponse: {
            error: {
                /** @description كود ثابت؛ يتعاقد المستهلك على الكود لا على ترجمة الرسالة. */
                code: string;
                message: string;
                /**
                 * @description تفاصيل بنيوية بلا إعادة قيمة المدخل؛ القيمة في رسالة خطأ تعيش في سجلات أوسع
                 *     صلاحية. الحقول **معدودة** لا حقيبة حرّة، وذاك بعينه ما يمنع «ضع القيمة في
                 *     التفاصيل». وهي مُعلَنة من MR 1/6 لأن `additionalProperties: false` بلا
                 *     `properties` تعني **لا مفتاح مسموح**، فكل تفصيل كان سيُفشل تحقّق مستهلكٍ صارم
                 *     على استجابةٍ صحيحة (درس Phase 05 · MR 4/6).
                 */
                details?: {
                    /** @description اسم الحقل المرفوض لا قيمته. */
                    field?: string;
                    /** @description وصف الشكل المتوقّع أو الانتقال المرفوض. */
                    expected?: string;
                    thread_state?: components["schemas"]["ThreadState"];
                    round_state?: components["schemas"]["RoundState"];
                    current_round_no?: number;
                    max_rounds?: number;
                    /** Format: int64 */
                    min_amount_minor?: number;
                    /** Format: int64 */
                    max_amount_minor?: number;
                    policy_version?: number;
                    /**
                     * @description اسم قيد القاعدة الذي كان سيرفض الكتابة نفسها؛ يجعل خطّ الدفاع الثاني قابلاً
                     *     للعثور بدلاً من افتراض أن القاعدة تعيش في TypeScript وحدها.
                     */
                    constraint?: string;
                };
            };
            trace_id: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً أو `Idempotency-Key` مفقود */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخيط أو الدور أو الاتفاق غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض في الحالة أو في إعادة استعمال مفتاح التفرّد أو دورٌ قديم */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخل صالح شكلياً ومرفوض بقاعدة أعمال أو سياسة أو مرجع خارجي */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة أو الاستمرارية في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ThreadId: string;
        /** @description رقم الدور داخل الخيط لا مُعرّفه العام؛ الترقيم المحليّ يجعل «الدور الثالث» عبارةً مفهومة للطرفين. */
        RoundNo: number;
        /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNegotiationThreads: {
        parameters: {
            query?: {
                orderPublicId?: components["schemas"]["OrderPublicId"];
                driverPublicId?: components["schemas"]["WaslaPublicId"];
                state?: components["schemas"]["ThreadState"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخيوط المطابقة، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThreadList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    openNegotiationThread: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadOpenRequest"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — يُعاد الخيط نفسه بلا فتح ثانٍ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThread"];
                };
            };
            /** @description فُتح الخيط ومعه الدور رقم 1 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThread"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getNegotiationThread: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخيط */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThread"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    cancelNegotiationThread: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCancelRequest"];
            };
        };
        responses: {
            /** @description أُغلق الخيط، أو كان مُغلقاً بالسبب نفسه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThread"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listNegotiationRounds: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الأدوار من الأول إلى الأخير */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationRoundList"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    proposeNegotiationRound: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundProposal"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — يُعاد الدور نفسه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationRound"];
                };
            };
            /** @description أُنشئ الدور */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationRound"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    acceptNegotiationRound: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
                /** @description رقم الدور داخل الخيط لا مُعرّفه العام؛ الترقيم المحليّ يجعل «الدور الثالث» عبارةً مفهومة للطرفين. */
                roundNo: components["parameters"]["RoundNo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundDecision"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — يُعاد الاتفاق نفسه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationAgreement"];
                };
            };
            /** @description وقع الاتفاق */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationAgreement"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    rejectNegotiationRound: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
                /** @description رقم الدور داخل الخيط لا مُعرّفه العام؛ الترقيم المحليّ يجعل «الدور الثالث» عبارةً مفهومة للطرفين. */
                roundNo: components["parameters"]["RoundNo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundRejection"];
            };
        };
        responses: {
            /** @description سُجّل الرفض */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationThread"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listNegotiationMessages: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الرسائل بترتيب التسلسل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationMessageList"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    postNegotiationMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageSubmission"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — تُعاد الرسالة نفسها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationMessage"];
                };
            };
            /** @description أُرسلت الرسالة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationMessage"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getNegotiationAgreement: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الاتفاق */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiationAgreement"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    tickNegotiations: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل فعل يُغيّر حالة، لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تُنتج دوراً ثانياً ولا رسالةً مضاعفة. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبّع عن حمولة العمل يمنع أن يصير المُعرّف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description اكتملت النبضة، وقد تكون العدّادات صفراً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حالة الخدمة وطبقة الاستمرارية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
