// registry.generated.ts — مُولَّدٌ من السجلِّ المرجعيِّ. لا يُحرَّرُ بيدٍ.
// المصدرُ: packages/config/env-registry.json
// التوليدُ: python3 scripts/config/render-config-artifacts.py
// والفحصُ 18 يُعيدُ التوليدَ ويقارنُ بايتاً بايتاً، فلا انحرافَ يمرُّ.

/** أنواعُ المتغيّراتِ المُعتَمدةُ — قائمةٌ مغلقةٌ. */
export type EnvVarType =
  | "postgres_url"
  | "http_url"
  | "port"
  | "positive_int"
  | "non_negative_int"
  | "string"
  | "csv"
  | "flag"
  | "secret_material";

/** درجةُ الإلزامِ: `conditional` تعني «إلزاميٌّ في حالةٍ مُسمّاةٍ». */
export type EnvRequirement = "always" | "conditional" | "optional";

/** موضعُ الاستهلاكِ: إنتاجٌ أو أداةٌ أو اختبارٌ. */
export type EnvScope = "runtime" | "tooling" | "test";

export interface EnvVarSpec {
  readonly name: string;
  readonly type: EnvVarType;
  readonly required: EnvRequirement;
  readonly secret: boolean;
  readonly default: string | null;
  readonly scopes: readonly EnvScope[];
  readonly readerCount: number;
  readonly ownerItem: string;
}

/** كلُّ متغيّرٍ مقروءٍ في الشجرةِ: 59 متغيّراً. */
export const ENV_REGISTRY: readonly EnvVarSpec[] = [
  {
    name: "COMMUNITY_GROUP_CHAT_IDS",
    type: "csv",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_DEEP_LINK_TEMPLATE",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_MINI_APP_LABEL",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_MINI_APP_URL",
    type: "http_url",
    required: "always",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: "8083",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_TOKEN",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_BOT_WEBHOOK_SECRET",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "CUSTOMER_DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["runtime", "test"],
    readerCount: 2,
    ownerItem: "M2-04",
  },
  {
    name: "DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["runtime", "test", "tooling"],
    readerCount: 71,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["test"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_ESCALATION_TIMEOUT_SECONDS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "120",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_MAX_WAVES",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "3",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_OFFER_TIMEOUT_SECONDS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "30",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DISPATCH_WAVE_SIZE",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "2",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_DEEP_LINK_TEMPLATE",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_MINI_APP_LABEL",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_MINI_APP_URL",
    type: "http_url",
    required: "always",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: "8084",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_TOKEN",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_BOT_WEBHOOK_SECRET",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["runtime", "test"],
    readerCount: 2,
    ownerItem: "M2-04",
  },
  {
    name: "DRIVER_DEV_ZONE_IDS",
    type: "csv",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ESCALATION_GROUP_CHAT_IDS",
    type: "csv",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "EXIT_GATE_REQUIRE_DB",
    type: "flag",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["test"],
    readerCount: 2,
    ownerItem: "M2-04",
  },
  {
    name: "GEOGRAPHY_BASE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: "http://localhost:8081",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "GEOGRAPHY_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 3,
    ownerItem: "M2-04",
  },
  {
    name: "IDEMPOTENCY_KEY_TTL_SECONDS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "86400",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "IDEMPOTENCY_SWEEP_BATCH_SIZE",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "500",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "IDEMPOTENCY_SWEEP_MAX_BATCHES",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "20",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "IDENTITY_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 4,
    ownerItem: "M2-04",
  },
  {
    name: "IDENTITY_TIMEOUT_MS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_PROBE_TIMEOUT_MS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: "1000",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_PROBE_TTL_MS",
    type: "non_negative_int",
    required: "optional",
    secret: false,
    default: "15000",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_SERVICE_HOST",
    type: "string",
    required: "optional",
    secret: false,
    default: "0.0.0.0",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_SERVICE_PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: "8094",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MARKETPLACE_TIMEOUT_MS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MATCHING_BASE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: "http://localhost:8093",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "MATCHING_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "NEGOTIATIONS_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 2,
    ownerItem: "M2-04",
  },
  {
    name: "NEGOTIATION_DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["test"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ORDERS_BASE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: "http://localhost:8087",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ORDERS_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ORDER_DATABASE_URL",
    type: "postgres_url",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["test"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ORDER_SERVICE_TIMEOUT_MS",
    type: "positive_int",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "ORDER_SERVICE_URL",
    type: "http_url",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_DEEP_LINK_TEMPLATE",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_MINI_APP_LABEL",
    type: "string",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_MINI_APP_URL",
    type: "http_url",
    required: "always",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: "8085",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_TOKEN",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PARTNER_BOT_WEBHOOK_SECRET",
    type: "secret_material",
    required: "always",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 12,
    ownerItem: "M2-04",
  },
  {
    name: "SUBSCRIPTION_SERVICE_HOST",
    type: "string",
    required: "optional",
    secret: false,
    default: "0.0.0.0",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "SUBSCRIPTION_SERVICE_PORT",
    type: "port",
    required: "optional",
    secret: false,
    default: "8095",
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "SUPPORT_GROUP_CHAT_IDS",
    type: "csv",
    required: "optional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 1,
    ownerItem: "M2-04",
  },
  {
    name: "WASLA_SERVICE_AUTH_ACTIVE_KID",
    type: "string",
    required: "conditional",
    secret: false,
    default: null,
    scopes: ["runtime"],
    readerCount: 5,
    ownerItem: "M2-04",
  },
  {
    name: "WASLA_SERVICE_AUTH_KEYS",
    type: "secret_material",
    required: "conditional",
    secret: true,
    default: null,
    scopes: ["runtime"],
    readerCount: 5,
    ownerItem: "M2-04",
  },
] as const;

/** أسماءُ المتغيّراتِ وحدَها — نوعٌ مغلقٌ يُستعملُ في القراءاتِ. */
export const ENV_VAR_NAMES = [
  "COMMUNITY_GROUP_CHAT_IDS",
  "CUSTOMER_BOT_DEEP_LINK_TEMPLATE",
  "CUSTOMER_BOT_MINI_APP_LABEL",
  "CUSTOMER_BOT_MINI_APP_URL",
  "CUSTOMER_BOT_PORT",
  "CUSTOMER_BOT_TOKEN",
  "CUSTOMER_BOT_WEBHOOK_SECRET",
  "CUSTOMER_DATABASE_URL",
  "DATABASE_URL",
  "DISPATCH_DATABASE_URL",
  "DISPATCH_ESCALATION_TIMEOUT_SECONDS",
  "DISPATCH_MAX_WAVES",
  "DISPATCH_OFFER_TIMEOUT_SECONDS",
  "DISPATCH_SERVICE_URL",
  "DISPATCH_WAVE_SIZE",
  "DRIVER_BOT_DEEP_LINK_TEMPLATE",
  "DRIVER_BOT_MINI_APP_LABEL",
  "DRIVER_BOT_MINI_APP_URL",
  "DRIVER_BOT_PORT",
  "DRIVER_BOT_TOKEN",
  "DRIVER_BOT_WEBHOOK_SECRET",
  "DRIVER_DATABASE_URL",
  "DRIVER_DEV_ZONE_IDS",
  "ESCALATION_GROUP_CHAT_IDS",
  "EXIT_GATE_REQUIRE_DB",
  "GEOGRAPHY_BASE_URL",
  "GEOGRAPHY_SERVICE_URL",
  "IDEMPOTENCY_KEY_TTL_SECONDS",
  "IDEMPOTENCY_SWEEP_BATCH_SIZE",
  "IDEMPOTENCY_SWEEP_MAX_BATCHES",
  "IDENTITY_SERVICE_URL",
  "IDENTITY_TIMEOUT_MS",
  "MARKETPLACE_PROBE_TIMEOUT_MS",
  "MARKETPLACE_PROBE_TTL_MS",
  "MARKETPLACE_SERVICE_HOST",
  "MARKETPLACE_SERVICE_PORT",
  "MARKETPLACE_SERVICE_URL",
  "MARKETPLACE_TIMEOUT_MS",
  "MATCHING_BASE_URL",
  "MATCHING_SERVICE_URL",
  "NEGOTIATIONS_SERVICE_URL",
  "NEGOTIATION_DATABASE_URL",
  "ORDERS_BASE_URL",
  "ORDERS_SERVICE_URL",
  "ORDER_DATABASE_URL",
  "ORDER_SERVICE_TIMEOUT_MS",
  "ORDER_SERVICE_URL",
  "PARTNER_BOT_DEEP_LINK_TEMPLATE",
  "PARTNER_BOT_MINI_APP_LABEL",
  "PARTNER_BOT_MINI_APP_URL",
  "PARTNER_BOT_PORT",
  "PARTNER_BOT_TOKEN",
  "PARTNER_BOT_WEBHOOK_SECRET",
  "PORT",
  "SUBSCRIPTION_SERVICE_HOST",
  "SUBSCRIPTION_SERVICE_PORT",
  "SUPPORT_GROUP_CHAT_IDS",
  "WASLA_SERVICE_AUTH_ACTIVE_KID",
  "WASLA_SERVICE_AUTH_KEYS",
] as const;

export type EnvVarName = (typeof ENV_VAR_NAMES)[number];

/** بحثٌ بالاسمِ — يُعيدُ `undefined` لغيرِ المُسجَّلِ لا يُلقي. */
export function findEnvVarSpec(name: string): EnvVarSpec | undefined {
  return ENV_REGISTRY.find((entry) => entry.name === name);
}
