/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قائمة نسخ الخطط
         * @description تُعاد النسخ كما خُزّنت، ولا يوجد مسار لتعديلها: خطة قابلة للتحرير تغيّر مدة مُنحت سابقاً بلا سجل.
         *     `frozen_only` يجعل المستهلك يطلب ما يصلح للاستعمال فعلاً بدلاً من تخمين معنى نسخة غير مجمدة.
         */
        get: operations["listSubscriptionPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/plans/{planCode}/{planVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة نسخة خطة مع امتيازاتها
         * @description النسخة جزء من عنوان المورد لا معلومة اختيارية في الاستجابة فقط: من دونها قد يطلب القارئ اسماً ثابتاً
         *     ويأخذ مدة تغيرت سراً. الامتيازات هنا كتالوج قراءة، لا سلطة لتفعيل أو منع سائق.
         */
        get: operations["getSubscriptionPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * بدء تجربة سائق بخطة مجمدة
         * @description البداية تنشئ منحة تجربة في الدفتر ثم تبني الحالة منها، لا صف حالة يدوي يتيم. مفتاح التفرّد إلزامي
         *     لأن إعادة محاولة المرسل بعد انقطاع الشبكة يجب أن تعيد المنحة نفسها لا أن تضيف تجربة ثانية.
         *
         *     الخطة غير المجمدة مرفوضة: استعمال نسخة قيد التحرير هو النسخة الأرخص من الحفظ التاريخي، ثم يصبح
         *     تفسير مدة لاحقة مستحيلاً بعد تغيير الكتالوج.
         */
        post: operations["startSubscriptionTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{driverPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة حالة اشتراك سائق المشتقة
         * @description `is_stale` مقصود لا عيب في الاستجابة: نهاية المدة تقارن بالوقت حتى قبل أن تعالجها النبضة،
         *     فيعرف القارئ أن الصف المتحقق يحتاج إعادة بناء. إخفاء ذلك خلف حالة تبدو حديثة أرخص لكنه قراءة كاذبة.
         */
        get: operations["getSubscriptionState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{driverPublicId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تفعيل اشتراك بإضافة مدة مدفوعة
         * @description المرجع المدفوع opaque ولا يفسر هنا؛ وظيفته وصل تسليم موثوق بمنحة مدة واحدة لا امتلاك قرار خارجي.
         *     تُضاف المدة إلى الدفتر ثم تشتق الحالة، فلا يعدل هذا الفعل تاريخاً سابقاً ولا يكتب رصيداً جانبياً.
         *
         *     مفتاح التفرّد إلزامي لأن المرسل قد يسلّم الإشارة نفسها أكثر من مرة. الاعتماد على فحص سابق غير ذري
         *     هو النسخة الأرخص التي تمنح مدة مضاعفة عند توازي الطلبات.
         */
        post: operations["activateSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{driverPublicId}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إعادة بناء الحالة من دفتر المُدد
         * @description هذا الطريق يثبت أن الحالة مشتقة لا أصل: حذف الصف المتحقق أو تصحيحه لا يخسر المنح، لأن الدفتر
         *     وحده يعيد بناءه. لا `requestBody` عمداً؛ الفعل على الحالة المخزنة، وإعلان جسم فارغ يجبر المرسل
         *     على اختراع معلومة لا يحتاجها الخادم.
         */
        post: operations["recomputeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{driverPublicId}/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة دفتر مُدد سائق
         * @description الدفتر يعرض المنح كما أضيفت ولا يحسب رصيداً موازياً. هذا أغنى من إرجاع نهاية واحدة لأن السؤال
         *     التشغيلي هو «أي منحة صنعت هذه النهاية؟»، والنسخة الأرخص تضيع جواب السؤال عند أول تجديد.
         */
        get: operations["listSubscriptionPeriods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة الإحالات بمُرشح إلزامي
         * @description واحد على الأقل من `referrer_public_id` أو `referee_public_id` أو `state` إلزامي. القراءة بلا مرشح
         *     تعني عرض شبكة الإحالات كلها بطلب واحد، وهو اختصار رخيص يتوسع بلا حد ويكشف أكثر مما يحتاجه المستهلك.
         *     الرفض يقرأ هنا بسبب مسمى؛ لا يحتاج إلى مسار كتابة يخلط الملاحظة بالحكم.
         */
        get: operations["listReferrals"];
        put?: never;
        /**
         * المطالبة بإحالة برمز موجود
         * @description المطالبة تسجل إحالة `pending` لا مكافأة فورية: التأهيل يبنى من وقائع المُحال، لا من التسجيل.
         *     مكافأة التسجيل تبدو أرخص لكنها تجعل إنشاء هويات خاملة طريقاً للحصول على منحة.
         *
         *     مفتاح التفرّد إلزامي لأن للمُحال إحالة واحدة فقط؛ القيد الذري يملك الحقيقة عند تزامن مطالبتين،
         *     وليس فحصاً مسبقاً يمر في العمليتين.
         */
        post: operations["claimReferral"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/codes/{ownerPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة رمز إحالة مالك
         * @description للمالك رمز واحد ظاهر صراحة بدلاً من توليد رمز جديد عند كل قراءة؛ التوليد المتكرر يخلق هويات
         *     تسويق متنافسة لمالك واحد ويصير تتبع الإحالة غير حاسم.
         */
        get: operations["getReferralCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * نبضة الزمن للتحقق من الانقضاء ومهلة المجتمع
         * @description النبضة هي المكان الوحيد الذي يثبت انتقالات الانقضاء ونهاية مهلة المجتمع. لا `requestBody` عمداً:
         *     العمل على الساعة وعلى الدفتر المخزن، وإضافة وقت من العميل تفتح باباً لساعة ثانية تختلف عن الحقيقة.
         *
         *     النبضة عملية جماعية؛ فشل سجل منفرد يعد في `failures` ولا يوقف بقية الاستحقاقات. رمي العملية كلها
         *     عند أول سجل هو النسخة الأرخص التي تخفي تراكم العمل المتأخر وراء إعادة محاولات لا تنتهي.
         */
        post: operations["tickSubscriptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فحص جاهزية الخدمة
         * @description وضع `memory` متدهور في التشغيل الحقيقي لأن الدفتر أصل لا يعاد بناؤه من صف الحالة. و`last_tick_at`
         *     يكشف غياب المنادي الدوري؛ إخفاء هذا الحقل أرخص لكنه يجعل زمن تقادم الحالة غير مرئي.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque للسائق أو المالك؛ لا يحلل ولا يعبر حد الخدمة كعلاقة قاعدة بيانات. */
        WaslaPublicId: string;
        ReferralCode: {
            referral_code: string;
            owner_public_id: components["schemas"]["WaslaPublicId"];
            /** @description الرمز معلن للقراءة، وتعطيله لا يستبدله برمز جديد للمالك نفسه. */
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        SubscriptionPlan: {
            plan_code: string;
            /** @description نسخة ثابتة من الكتالوج؛ الاسم وحده ليس مرجعاً تاريخياً كافياً. */
            plan_version: number;
            label: string;
            trial_days: number;
            duration_days: number;
            community_grace_days: number;
            /** @description لا تمنح مدة من نسخة غير مجمدة؛ التعديل في المكان يبدل الماضي بلا أثر تدقيقي. */
            is_frozen: boolean;
            entitlements: components["schemas"]["SubscriptionPlanEntitlement"][];
        };
        SubscriptionPlanList: {
            plans: components["schemas"]["SubscriptionPlan"][];
        };
        SubscriptionPlanEntitlement: {
            /**
             * @description قائمة مغلقة؛ امتياز جديد يحتاج قراراً معلناً لا نصاً يفسره كل مستهلك بطريقته.
             * @enum {string}
             */
            entitlement_code: "accept_orders" | "daily_order_cap" | "priority_dispatch" | "zone_multi_select";
            /** @description قيمة سالب واحد تعني بلا سقف، وعدد صحيح يبقى قابلاً للمقارنة بلا تقريب. */
            limit_value: number;
        };
        SubscriptionState: {
            driver_public_id: components["schemas"]["WaslaPublicId"];
            /** Format: uuid */
            subscription_id: string;
            /**
             * @description حالة مشتقة من الدفتر وجدول الانتقالات المعلن، لا قيمة يكتبها مسار إدارة حر.
             * @enum {string}
             */
            state: "trial" | "active" | "expired" | "community";
            plan_code: string;
            plan_version: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** @description ترتيب انتقال الحالة للسائق؛ يبقى سبب الترتيب قابلاً للاستعادة من الدفتر. */
            state_sequence: number;
            /** @description يعلن أن الزمن تجاوز نهاية مخزنة قبل النبضة، بدلاً من إظهار حالة قديمة كأنها حديثة. */
            is_stale: boolean;
            entitlements: components["schemas"]["SubscriptionPlanEntitlement"][];
            /** Format: date-time */
            computed_at: string;
        };
        SubscriptionStartRequest: {
            driver_public_id: components["schemas"]["WaslaPublicId"];
            plan_code: string;
            plan_version: number;
            /**
             * Format: date-time
             * @description زمن طلب البداية؛ تسجل الخدمة زمن المنحة الناتجة صراحة في الدفتر.
             */
            requested_at: string;
        };
        SubscriptionStartResult: {
            subscription: components["schemas"]["SubscriptionState"];
            period: components["schemas"]["SubscriptionPeriod"];
            /** @description يفرق صراحة بين كتابة جديدة وجواب محفوظ من إعادة محاولة، بدلاً من جعل `200` تخميناً. */
            duplicate: boolean;
        };
        SubscriptionActivateRequest: {
            /** @description مرجع opaque للتحصيل؛ لا يفسر ولا يبحث عنه هذا العقد. */
            payment_reference: string;
            plan_code: string;
            plan_version: number;
            /** Format: date-time */
            activated_at: string;
        };
        SubscriptionActivateResult: {
            subscription: components["schemas"]["SubscriptionState"];
            period: components["schemas"]["SubscriptionPeriod"];
            duplicate: boolean;
        };
        SubscriptionRecomputeResult: {
            subscription: components["schemas"]["SubscriptionState"];
            /** @description يعلن أن الصف المتحقق أعيد من الدفتر، حتى إن ساوت النتيجة الحالة السابقة. */
            rebuilt: boolean;
        };
        SubscriptionPeriod: {
            /** Format: uuid */
            period_id: string;
            driver_public_id: components["schemas"]["WaslaPublicId"];
            plan_code: string;
            plan_version: number;
            /** @enum {string} */
            source: "trial" | "payment" | "referral_reward";
            /** @description موجود فقط لمنحة مصدرها `payment`؛ لا يوجد حقل بديل لمنح الإحالة أو التجربة. */
            payment_reference: string | null;
            granted_days: number;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            created_at: string;
        };
        SubscriptionPeriodList: {
            periods: components["schemas"]["SubscriptionPeriod"][];
        };
        Referral: {
            /** Format: uuid */
            referral_id: string;
            referral_code: string;
            referrer_public_id: components["schemas"]["WaslaPublicId"];
            referee_public_id: components["schemas"]["WaslaPublicId"];
            /** @enum {string} */
            state: "pending" | "qualified" | "rewarded" | "rejected";
            /**
             * @description سبب مغلق للرفض فقط؛ الصمت لا يفرق بين قاعدة مرفوضة وتأخر في المعالجة.
             * @enum {string|null}
             */
            reason_code: "self_referral" | "referrer_not_active" | "referee_already_referred" | "referee_no_qualifying_facts" | "referral_window_expired" | "referee_subscription_never_activated" | null;
            qualifying_fact_count: number;
            /** Format: date-time */
            window_ends_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            state_changed_at: string;
            reward: components["schemas"]["ReferralReward"] | null;
        };
        ReferralList: {
            referrals: components["schemas"]["Referral"][];
        };
        ReferralClaimRequest: {
            referral_code: string;
            referee_public_id: components["schemas"]["WaslaPublicId"];
            /** Format: date-time */
            claimed_at: string;
        };
        ReferralClaimResult: {
            referral: components["schemas"]["Referral"];
            /** @description يعلن جواب المطالبة المحفوظ صراحة كي لا يعده العميل مطالبة جديدة. */
            duplicate: boolean;
        };
        ReferralReward: {
            /** Format: uuid */
            reward_id: string;
            /** Format: uuid */
            referral_id: string;
            /** Format: uuid */
            granted_period_id: string;
            reward_days: number;
            plan_code: string;
            plan_version: number;
            /** Format: date-time */
            created_at: string;
        };
        TickResult: {
            /** Format: date-time */
            ran_at: string;
            periods_ended: number;
            subscriptions_expired: number;
            subscriptions_moved_to_community: number;
            referrals_qualified: number;
            rewards_applied: number;
            /** @description تعد الحالات الفردية الفاشلة ولا توقف معالجة بقية السجلات المستحقة. */
            failures: number;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            /** @enum {string} */
            mode: "postgres" | "memory";
            /**
             * Format: date-time
             * @description آخر نبضة نفذت في هذه العملية، و`null` قبل أول نبضة.
             */
            last_tick_at: string | null;
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "SUBSCRIPTION_VALIDATION_FAILED" | "SUBSCRIPTION_IDEMPOTENCY_KEY_REQUIRED" | "SUBSCRIPTION_FILTER_REQUIRED" | "SUBSCRIPTION_NOT_FOUND" | "SUBSCRIPTION_PLAN_NOT_FOUND" | "REFERRAL_CODE_NOT_FOUND" | "SUBSCRIPTION_IDEMPOTENCY_KEY_REUSED" | "SUBSCRIPTION_PLAN_NOT_FROZEN" | "SUBSCRIPTION_PAYMENT_REFERENCE_REQUIRED" | "REFERRAL_SELF_FORBIDDEN" | "REFERRAL_WINDOW_CLOSED" | "REFERRAL_REFEREE_NOT_QUALIFIED" | "SUBSCRIPTION_UNAVAILABLE";
                message: string;
                /**
                 * @description تفاصيل بنيوية بلا إعادة قيمة المدخل. الحقول معدودة لا حقيبة حرة؛ فتحها بلا عقد يجعل
                 *     المستهلك الصارم يفشل عند أول مفتاح جديد في استجابة صحيحة.
                 */
                details?: {
                    /** @description اسم الحقل المرفوض لا قيمته. */
                    field?: string;
                    /** @description شكل متوقع أو قاعدة معلنة. */
                    expected?: string;
                    driver_public_id?: components["schemas"]["WaslaPublicId"];
                    plan_code?: string;
                    plan_version?: number;
                    referral_code?: string;
                    /** @enum {string} */
                    state?: "trial" | "active" | "expired" | "community" | "pending" | "qualified" | "rewarded" | "rejected";
                    /** @description اسم القيد الذي يحمي الحقيقة نفسها عند تزامن الكتابة. */
                    constraint?: string;
                };
            };
            trace_id: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً أو مفتاح تفرّد مفقود أو مرشح قراءة ناقص */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description اشتراك أو خطة أو رمز إحالة غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مفتاح تفرّد أعيد مع طلب مختلف */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخل صالح شكلياً ومرفوض بقاعدة حالة أو تأهيل أو خطة */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة أو طبقة الاستمرارية غير متاحة */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description مُعرّف السائق العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
        DriverPublicId: components["schemas"]["WaslaPublicId"];
        /** @description المالك سائق أيضاً، ويستعمل النمط العام نفسه كي لا يقدم المسار نوع معرف ثانياً. */
        OwnerPublicId: components["schemas"]["WaslaPublicId"];
        PlanCode: string;
        PlanVersion: number;
        /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSubscriptionPlans: {
        parameters: {
            query?: {
                /** @description عند `true` لا تظهر إلا النسخ المسموح أن تمنح مُدداً. */
                frozen_only?: boolean;
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description نسخ الخطط المطابقة مع امتيازاتها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlanList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSubscriptionPlan: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                planCode: components["parameters"]["PlanCode"];
                planVersion: components["parameters"]["PlanVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخطة المجمدة أو غير المجمدة بنسختها الصريحة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlan"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    startSubscriptionTrial: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionStartRequest"];
            };
        };
        responses: {
            /** @description مفتاح التفرّد نفسه عولج سابقاً؛ تعاد النتيجة المحفوظة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStartResult"];
                };
            };
            /** @description بدأت التجربة وسجلت مدتها في الدفتر */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStartResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSubscriptionState: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف السائق العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
                driverPublicId: components["parameters"]["DriverPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الحالة ونسخة الخطة والامتيازات المشتقة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionState"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    activateSubscription: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف السائق العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
                driverPublicId: components["parameters"]["DriverPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionActivateRequest"];
            };
        };
        responses: {
            /** @description أضيفت المدة وأعيد اشتقاق الحالة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionActivateResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    recomputeSubscription: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف السائق العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
                driverPublicId: components["parameters"]["DriverPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description أعيدت الحالة من الدفتر، سواء اختلفت أم بقيت كما كانت */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRecomputeResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listSubscriptionPeriods: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف السائق العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
                driverPublicId: components["parameters"]["DriverPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description مدد السائق بترتيب الإنشاء */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPeriodList"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listReferrals: {
        parameters: {
            query?: {
                referrer_public_id?: components["schemas"]["WaslaPublicId"];
                referee_public_id?: components["schemas"]["WaslaPublicId"];
                state?: "pending" | "qualified" | "rewarded" | "rejected";
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الإحالات المطابقة، أحدثها أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralList"];
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    claimReferral: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralClaimRequest"];
            };
        };
        responses: {
            /** @description مفتاح التفرّد نفسه عولج سابقاً؛ تعاد النتيجة المحفوظة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralClaimResult"];
                };
            };
            /** @description سُجلت الإحالة بانتظار التأهيل */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralClaimResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getReferralCode: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description المالك سائق أيضاً، ويستعمل النمط العام نفسه كي لا يقدم المسار نوع معرف ثانياً. */
                ownerPublicId: components["parameters"]["OwnerPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description رمز الإحالة وحالة صلاحيته */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralCode"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    tickSubscriptions: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير الدفتر أو الحالة؛ إعادة المحاولة تعيد جواباً محفوظاً ولا تنشئ منحة أو مطالبة ثانية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع خلط المعرّف التشغيلي ببيانات المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description اكتملت النبضة، وقد تكون جميع العدادات صفراً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حالة الخدمة وطبقة الاستمرارية وآخر نبضة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
