/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * حالة الخدمة
         * @description `ok` فقط عندما تكون الخدمة قادرة على إتمام عملها (تخزين دائم مضبوط ونسخة قواعد
         *     مُقفَلة موجودة)؛ وإلّا `degraded`. خدمة مطابقة بلا نسخة قواعد لا تستطيع أن تُرتّب،
         *     وقولها «سليمة» يُخفي عطلاً يظهر عند أول طلب حقيقي.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description الحالة */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @constant */
                            service: "matching-service";
                            /** @enum {string} */
                            persistence: "postgres" | "memory";
                            active_ruleset_version: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قائمة مرشّحين مرتّبة لطلب
         * @description فلاتر صلبة أولاً (§30.1) ثمّ درجة موزونة (§30.2 بأوزان النسخة). العملية **قراءة
         *     وتقييم وكتابة صفّ تدقيق** — لا أثر تشغيلي آخر.
         *
         *     `evaluated_at` **مُدخَل اختياري صريح** لا `now()` مخفيّ: مُدخَلات العدالة فوارق زمنية،
         *     وترتيبٌ لا يمكن إعادة إنتاجه بحرفه ترتيبٌ لا يمكن الدفاع عنه أمام شكوى سائق.
         *     إن غاب تُستعمَل ساعة الخدمة، ويُسجَّل ما استُعمِل في صفّ التدقيق على الحالين.
         *
         *     `excluded_driver_ids` من واجب المُنادي (§17): من رفض أو انتهت مهلته في المهمّة نفسها
         *     لا يُعاد عليه العرض. المطابقة تُطيع ولا تسأل عن السبب — هي لا تعرف المهمّة.
         *
         *     قائمة فارغة **ليست خطأً**: `200` بمصفوفة فارغة و`empty_reason_code` من الكتالوج.
         *     رمز خطأ هنا يجعل «لا سائق متاح الآن» يبدو عطلاً في النظام فيُوقظ من لا شأن له.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description يصبح `trace_id` في الرد وفي صفّ التدقيق. */
                    "x-request-id"?: components["parameters"]["RequestId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CandidateQuery"];
                };
            };
            responses: {
                /** @description التقييم تمّ (وقد يكون بلا مرشّحين) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandidateResult"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /**
                 * @description صالح شكلياً ومرفوض منطقياً: منطقة غير موجودة في هرم الجغرافيا، أو نسخة قواعد
                 *     مطلوبة غير مُقفَلة. لا نُرتّب بقواعد قابلة للتحرير.
                 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidacy/{driverPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة صفّ الترشيح
         * @description للتشغيل والتدقيق ولبوت السائق ليعرض على صاحبه ما يراه النظام عنه.
         *     لا يُعاد فيه شيء لم يكتبه المُنادي أصلاً.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    driverPublicId: components["parameters"]["DriverPublicId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description الصفّ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidacy"];
                    };
                };
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        /**
         * استبدال صفّ الترشيح لسائق
         * @description **استبدال كامل لا دمج جزئي**: دمجٌ جزئي على إسقاط يُنتج خلائط لا يقصدها أحد
         *     (توافر جديد مع مناطق قديمة). المُنادي اليوم بوت السائق والإدارة، ويصير Driver Core
         *     (Phase 05) صاحب الحقّ فيه بلا هجرة ولا تغيير في الجدول.
         *
         *     `updated_at` تكتبه الخدمة لا المُنادي: عمود الحداثة هو عمود القرار في fail-closed،
         *     وتركه للمُنادي يجعل «حديث» ادّعاءً آخر.
         */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description يصبح `trace_id` في الرد وفي صفّ التدقيق. */
                    "x-request-id"?: components["parameters"]["RequestId"];
                };
                path: {
                    driverPublicId: components["parameters"]["DriverPublicId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CandidacyUpsert"];
                };
            };
            responses: {
                /** @description الصفّ بعد الاستبدال */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidacy"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description نفس `Idempotency-Key` بحمولة مختلفة */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description منطقة غير موجودة، أو صنف مركبة خارج القائمة المُقفلة */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidacy/{driverPublicId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تغيير التوافر وحده (متاح · مشغول · غير متصل)
         * @description مسار ضيّق لأكثر عملية تكراراً في النظام (§78 «Busy/free transitions»): يُنادى عند
         *     قبول السائق طلباً (`busy`) وعند وصول الطلب إلى حالة نهائية (`available`) وعند إعلان
         *     السائق انسحابه (`offline`).
         *
         *     مفصول عن `PUT /candidacy/{id}` لأن الاستبدال الكامل يحتاج كل الحقول، ومن يريد تغيير
         *     التوافر وحده كان سيُضطرّ إلى قراءةٍ قبل كل كتابة — أو إلى مسح مناطقه بالخطأ.
         *
         *     سائق **بلا صفّ** يُجيب `404`: التوافر صفة على ترشيح قائم لا إنشاء ضمنيّ له، وإنشاء
         *     صفّ من نداء توافر يُنتج مرشّحاً بلا أهليّة ولا مناطق.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description يصبح `trace_id` في الرد وفي صفّ التدقيق. */
                    "x-request-id"?: components["parameters"]["RequestId"];
                };
                path: {
                    driverPublicId: components["parameters"]["DriverPublicId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        availability_state: "available" | "busy" | "offline";
                        actor_type?: components["schemas"]["ActorType"];
                    };
                };
            };
            responses: {
                /** @description الصفّ بعد التغيير */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidacy"];
                    };
                };
                400: components["responses"]["ValidationError"];
                404: components["responses"]["NotFound"];
                /** @description نفس `Idempotency-Key` بحمولة مختلفة */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * نسخ قواعد الترتيب
         * @description الأوزان **معلومة عامّة للتشغيل**: من يسأل «لماذا رُتِّب السائقون هكذا؟» يقرأ النسخة
         *     لا الكود. والنسخة المُقفَلة لا تُحرَّر أبداً — تحريرها يُعيد كتابة تاريخ قرارات
         *     لا يمكن تفسيرها بعده.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description النسخ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rulesets: components["schemas"]["Ruleset"][];
                        };
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/decisions/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قرار مطابقة واحد بدرجاته
         * @description يجيب عن «لماذا هذا السائق ولم يكن ذاك؟» بعد شهر. **مسار تشغيل وتدقيق لا مسار عام**:
         *     محتواه مُعرّفات مرشّحين ودرجاتهم، وهي بيانات حسّاسة تنافسياً عن السائقين
         *     (ADR-011 القرار 8) لا تُعاد لعميل ولا لسائق ولا تدخل حمولة حدث.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    decisionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description القرار */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Decision"];
                    };
                };
                404: components["responses"]["NotFound"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque. لا يُحلَّل ولا تُقرأ أجزاؤه. */
        WaslaPublicId: string;
        /**
         * Format: uuid
         * @description مُعرّف منطقة من هرم الجغرافيا (ADR-006). النوع UUID كما في كل خدمة أخرى، والقرب
         *     يُحسَب بالهرم لا بالمساواة: المنطقة نفسها أو ما يشمله أصل مخدوم.
         */
        ZoneRef: string;
        /** @description مُعرّف الطلب العام. نصّ opaque لا رقم (ADR-010 القرار 5). */
        OrderPublicId: string;
        /**
         * @description من نفّذ العملية — كود جهة لا مُعرّف مستخدم ولا مُعرّف قناة (ADR-007).
         * @enum {string}
         */
        ActorType: "driver_bot" | "admin" | "driver_core" | "dispatch" | "test";
        /**
         * @description حقائق الطلب التي تدخل الفلاتر الصلبة فقط. **لا نصّ كتبه مستخدم** (وصف شحنة · ملاحظات ·
         *     تسمية مكان) ولا إحداثيات: الجغرافيا هرم مُعرّفات (ADR-006)، والخصوصية حدّ لا تجميل
         *     (ADR-010 القرار 7).
         */
        CandidateQuery: {
            /** Format: uuid */
            order_id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            /** @enum {string} */
            order_type: "ride" | "delivery";
            /**
             * @description القائمة مُقفلة ومطابقة حرفياً لعقد الطلب — نقص عنصر يُخفي مرشّحاً صالحاً.
             * @enum {string}
             */
            vehicle_class: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
            pickup_zone_id: components["schemas"]["ZoneRef"];
            /** @description من لا يُعاد عليه العرض في هذه المهمّة (§17). واجب المُنادي لأنه مالك المهمّة. */
            excluded_driver_ids?: components["schemas"]["WaslaPublicId"][];
            /** @description سقف المُعاد. الافتراضي `max_candidates` من نسخة القواعد. */
            limit?: number;
            /** @description للاختبار وإعادة إنتاج قرار قديم. الافتراضي أحدث نسخة مُقفَلة. */
            ruleset_version?: number;
            /**
             * Format: uuid
             * @description يُحفَظ في صفّ التدقيق للربط في التحقيق **ولا يدخل المنطق** (وإلّا انعكس الاعتماد).
             */
            dispatch_job_id?: string;
            /**
             * Format: date-time
             * @description ساعة التقييم. مُدخَل صريح ليكون الترتيب قابلاً لإعادة الإنتاج حرفياً.
             */
            evaluated_at?: string;
        };
        RankedCandidate: {
            rank: number;
            driver_public_id: components["schemas"]["WaslaPublicId"];
            /**
             * @description الدرجة بأعداد صحيحة من عشرة آلاف لا بعشريات: المقارنة تامّة والترتيب قابل
             *     لإعادة الإنتاج. المقارنة العشرية تجعل تعادلاً حقيقياً يبدو فرقاً.
             */
            score_bp: number;
            /** @description مكوّنات الدرجة — للتفسير والتدقيق لا للمنطق عند المُستهلِك. */
            components?: {
                zone_proximity_bp?: number;
                completion_bp?: number;
                acceptance_bp?: number;
                fairness_bp?: number;
            };
            /**
             * @description كيف حُسم موضعه — مُعلَن لا عشوائي (ADR-011 القرار 6).
             * @enum {string}
             */
            tiebreak_by?: "score" | "last_offered_at" | "driver_public_id";
        };
        CandidateResult: {
            /**
             * Format: uuid
             * @description مرجع صفّ التدقيق. يُحفظ عند المُنادي ليُسأل عنه لاحقاً.
             */
            decision_id: string;
            ruleset_version: number;
            /** Format: date-time */
            evaluated_at: string;
            candidates: components["schemas"]["RankedCandidate"][];
            /**
             * @description ثلاثة أعداد تُفسّر النتيجة الفارغة بلا تخمين: كم صفّاً نُظر فيه، كم عبر الفلاتر
             *     الصلبة، وكم أُعيد بعد السقف.
             */
            counts: {
                considered: number;
                eligible: number;
                returned: number;
            };
            /**
             * @description إلزامي عند القائمة الفارغة: كود من كتالوج [errors.md](errors.md) — «صفر مرشّح»
             *     بلا سبب أسوأ من خطأ، لأنه لا يقول للمشغّل أين يبحث.
             */
            empty_reason_code?: string;
        };
        CandidacyUpsert: {
            /** @enum {string} */
            availability_state: "available" | "busy" | "offline";
            /**
             * @description **مُدّعاة لا مُتحقَّقة** حتى Phase 05. الافتراضي الصادق `unknown` لا `eligible`:
             *     الافتراضي المتساهل يُنتج عروضاً لسائقين لا نعرف عنهم شيئاً.
             * @enum {string}
             */
            eligibility_state: "eligible" | "ineligible" | "suspended" | "unknown";
            /**
             * @description من قال هذا. يُخزَّن مع الصفّ فلا يُقرأ الادّعاء تحقّقاً بعد شهر.
             * @enum {string}
             */
            eligibility_source?: "claimed" | "driver_core";
            service_kinds: ("ride" | "delivery")[];
            /** @enum {string|null} */
            vehicle_class?: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small" | null;
            /** @description المناطق المخدومة. التطابق بالهرم لا بالمساواة: المنطقة نفسها أو ما يشمله أصل مخدوم. */
            zone_ids: components["schemas"]["ZoneRef"][];
            actor_type?: components["schemas"]["ActorType"];
        };
        Candidacy: {
            driver_public_id: components["schemas"]["WaslaPublicId"];
            /** @enum {string} */
            availability_state: "available" | "busy" | "offline";
            /** @enum {string} */
            eligibility_state: "eligible" | "ineligible" | "suspended" | "unknown";
            /** @enum {string} */
            eligibility_source: "claimed" | "driver_core";
            service_kinds: ("ride" | "delivery")[];
            vehicle_class?: string | null;
            zone_ids: components["schemas"]["ZoneRef"][];
            /** Format: date-time */
            last_offered_at?: string | null;
            /** Format: date-time */
            last_assigned_at?: string | null;
            offers_received?: number;
            offers_accepted?: number;
            orders_completed?: number;
            /**
             * @description هل الصفّ داخل نافذة الحداثة **الآن**؟ محسوب لا مخزَّن: من يقرأ يحتاج الجواب،
             *     ومن يكتبه في القاعدة يُنتج عموداً يكذب بمرور الوقت وحده.
             */
            is_fresh?: boolean;
            /** Format: date-time */
            updated_at: string;
            updated_by?: string;
        };
        Ruleset: {
            version: number;
            label: string;
            /**
             * @description نقاط مئوية صحيحة مجموعها 100 بالضبط (قيد في القاعدة). أوزان الصفر مذكورة
             *     صراحةً ولا تُحذف: الصفر المُعلَن يقول «المُدخَل غير موجود اليوم»، والحذف يقول
             *     «لم يفكّر أحد فيه».
             */
            weights: {
                eta?: number;
                distance?: number;
                zone_proximity?: number;
                completion?: number;
                rating?: number;
                acceptance?: number;
                fairness?: number;
            };
            candidacy_freshness_seconds?: number;
            max_candidates?: number;
            fairness_horizon_seconds?: number;
            /** @description النسخة المُستعمَلة مُقفَلة لا تُحرَّر. التعديل نسخة جديدة. */
            is_frozen: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        Decision: {
            /** Format: uuid */
            decision_id: string;
            /** Format: uuid */
            order_id: string;
            order_public_id?: components["schemas"]["OrderPublicId"];
            /** Format: uuid */
            dispatch_job_id?: string | null;
            ruleset_version: number;
            /** Format: date-time */
            requested_at?: string;
            /** Format: date-time */
            evaluated_at: string;
            counts: {
                considered?: number;
                eligible?: number;
                returned?: number;
                excluded?: number;
            };
            empty_reason_code?: string | null;
            candidates: components["schemas"]["RankedCandidate"][];
        };
        ErrorResponse: {
            /** @description كود ثابت (stable) — الاختبارات تتحقّق منه لا من النص */
            code: string;
            message: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الكيان غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description صالح شكلياً وغير مقبول منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DriverPublicId: components["schemas"]["WaslaPublicId"];
        /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الرد وفي صفّ التدقيق. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
