/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * حالة الخدمة
         * @description `ok` فقط عندما تكون الخدمة قادرة على إتمام عملها (تخزين دائم مضبوط)؛
         *     وإلّا `degraded`. خدمة تقول «سليمة» وهي لا تستطيع كتابة طلب تُخفي عطلاً.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description الحالة */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @constant */
                            service: "orders-service";
                            /** @enum {string} */
                            persistence: "postgres" | "memory";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * استقبال نيّة طلب مُتحقَّقة وإنشاء طلب
         * @description الطرف الآخر لـ`OrderIntakePort`. يُنشئ طلباً بحالة `published` ويُصدر `order_public_id`.
         *
         *     **الدلالة مُثبَّتة باختبار من الطرف المُسلِّم** ([بوابة Phase 04](../../../docs/12-testing/PHASE04_EXIT_GATE_E2E.md)):
         *     - `201` أُنشئ · `200` إعادة نفس المفتاح بنفس الحمولة (بلا صفّ ثانٍ وبلا حدث ثانٍ)
         *     - `400` الجسم لا يطابق العقد — يعامله المُسلِّم **كخطئه** (`UNAVAILABLE`) لا كرفض تجاري
         *     - `409` نفس المفتاح بحمولة مختلفة
         *     - `422` صالح شكلياً ومرفوض منطقياً (منطقة غير مقبولة · تناقض سعر)
         */
        post: operations["intakeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة طلب (مُقيَّدة بالمالك) */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * سجل تدقيق الانتقالات (مُرتَّب تصاعدياً)
         * @description كل انتقال حدث للطلب، بلا استثناء — هو الدليل على أنّ الحالة لم تتغيّر صامتة.
         */
        get: operations["getOrderHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تغيير حالة الطلب — المسار الوحيد
         * @description ينجح فقط إذا كان الزوج (الحالة الحالية، `to_status`) **مذكوراً في جدول الانتقالات**
         *     (ADR-010 القرار 3). وإلّا **409** `ORDER_ILLEGAL_TRANSITION` مع `from` و`to` في التفاصيل.
         *
         *     يكتب صفّ تدقيق ويُنتج حدثاً **في المعاملة نفسها**. `reason_code` إلزامي لكل حالة نهائية.
         *     والحالات التي تُسمّي سائقاً تستلزم إسناداً نشطاً مُسجَّلاً مسبقاً وإلّا **422**.
         */
        post: operations["transitionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تسجيل عرض إسناد لسائق (سجل لا قرار)
         * @description Phase 07 تُقرّر **من** يُعرض عليه ومتى؛ هذا المسار يسجّل ما قرّرته (§16).
         *     `driver_public_id` مرجع opaque — لا يتحقّق المحرّك من أهلية السائق (ADR-010 القرار 4).
         *     عرض الطلب نفسه على السائق نفسه مرّتين ⇒ **409**.
         */
        post: operations["recordAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/assignments/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * تحديث حالة عرض الإسناد (قبول · رفض · انتهاء · إلغاء)
         * @description القبول هو ما يجعل الإسناد **نشطاً** على الطلب، فيصبح الانتقال إلى الحالات التي
         *     تُسمّي سائقاً ممكناً. الرفض والانتهاء لا يُنهيان الطلب (ADR-010 القرار 3.5).
         */
        patch: operations["updateAssignmentState"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque. لا يُحلَّل ولا تُقرأ أجزاؤه. */
        WaslaPublicId: string;
        /**
         * @description يملكه المحرّك ويُولَّد من متتالية في القاعدة (ADR-010 القرار 5).
         *     **نصّ opaque للمستهلكين**: لا يُحلَّل ولا يُشتَقّ منه ترتيب ولا عدد.
         */
        OrderPublicId: string;
        /** @description كود من كتالوج [errors.md](errors.md) — **لا نصّ حرّ** ولا نصّ كتبه مستخدم. */
        ReasonCode: string;
        /**
         * @description دورة الحياة كما قيّدها ADR-010 عن §15.1: **لا `draft`**،
         *     و`driver_rejected`/`driver_timeout` **عابرتان** لا نهايتان.
         * @enum {string}
         */
        OrderStatus: "published" | "searching" | "offered" | "negotiating" | "accepted" | "assigned" | "driver_en_route" | "arrived" | "in_progress" | "completed" | "driver_rejected" | "driver_timeout" | "expired" | "no_driver_found" | "customer_cancelled" | "driver_cancelled" | "partner_cancelled" | "blocked" | "failed" | "payment_disputed" | "under_review";
        /** @enum {string} */
        OrderType: "ride" | "delivery";
        /**
         * @description مطابقة حرفياً لعقد خدمة العميل. أي نقص يجعل المحرّك يرفض طلباً صالحاً.
         * @enum {string}
         */
        VehicleClass: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
        /** @enum {string} */
        PriceMode: "customer_offer" | "negotiable";
        /** @enum {string} */
        StopKind: "pickup" | "dropoff";
        /** @enum {string} */
        StopSource: "map" | "telegram_location" | "link" | "text_search" | "saved_place" | "manual_zone";
        /** @enum {string} */
        ActorType: "system" | "customer" | "driver" | "partner" | "admin";
        /** @enum {string} */
        AssignmentState: "offered" | "accepted" | "rejected" | "expired" | "cancelled";
        Money: {
            /**
             * Format: int64
             * @description بالوحدة الصغرى (هللة) — **عدد صحيح**. لا عدد عشري في المال أبداً.
             */
            amount_minor: number;
            currency: string;
        };
        Stop: {
            kind: components["schemas"]["StopKind"];
            /**
             * Format: uuid
             * @description إلزامي — نقطة بلا منطقة غير قابلة للمطابقة (ADR-009 القرار 2).
             */
            zone_id: string;
            label?: string | null;
            source: components["schemas"]["StopSource"];
            /** Format: uuid */
            saved_place_id?: string | null;
            latitude?: number | null;
            longitude?: number | null;
        };
        ShipmentDetails: {
            /** @enum {string|null} */
            shipment_type?: "parcel" | "documents" | "food" | "goods" | "other" | null;
            description?: string | null;
            weight_kg?: number | null;
        };
        /**
         * @description **مرآة** لـ`OrderIntakeRequest` في
         *     [عقد خدمة العميل](../../customers/contracts/api.openapi.yml): الحقول المطلوبة وأسماؤها
         *     وقوائمها المُقفلة متطابقة، وحارس عقد في `@wasla/contracts-order` يُفشل البناء عند أي انحراف
         *     فيها — لأن الانحراف يكسر بوابة خروج Phase 04.
         *
         *     **فرق واحد مقصود:** هنا `maxItems: 2` على `stops`. المُسلِّم يتحقّق من «نقطتان بالضبط»
         *     في مجاله (ADR-009 القرار 3) ولم يُثبّت الحدّ الأعلى في مخطّطه؛ والمحرّك يُثبّته لأنّه
         *     الطرف الذي يستقبل من الشبكة: قبول ثلاث نقاط هنا يعني تخزين طلب لا يستطيع أحد مطابقته.
         */
        OrderIntakeRequest: {
            /** Format: uuid */
            order_request_id: string;
            customer_public_id: components["schemas"]["WaslaPublicId"];
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            price_mode: components["schemas"]["PriceMode"];
            offered_price?: components["schemas"]["Money"] | null;
            /** @description نقطتان بالضبط في هذه المرحلة (ADR-009 القرار 3). */
            stops: components["schemas"]["Stop"][];
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
            /** Format: date-time */
            requested_at: string;
            idempotency_key?: string;
        };
        OrderIntakeResult: {
            order_public_id: components["schemas"]["OrderPublicId"];
            /** Format: date-time */
            accepted_at: string;
        };
        TransitionRequest: {
            to_status: components["schemas"]["OrderStatus"];
            reason_code?: components["schemas"]["ReasonCode"];
            actor_type: components["schemas"]["ActorType"];
            /** @description مُعرّف عام للفاعل البشري. إلزامي لكل `actor_type` غير `system`، وممنوع مع `system`. */
            actor_ref?: components["schemas"]["WaslaPublicId"] | null;
        };
        Assignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            driver_public_id: components["schemas"]["WaslaPublicId"];
            sequence: number;
            assignment_state: components["schemas"]["AssignmentState"];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Format: date-time */
            offered_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            rejected_at?: string | null;
            /** Format: date-time */
            expired_at?: string | null;
            /** Format: date-time */
            cancelled_at?: string | null;
        };
        StatusHistoryEntry: {
            sequence: number;
            /** @description `null` مرّة واحدة فقط: عند الإنشاء. */
            from_status?: components["schemas"]["OrderStatus"] | null;
            to_status: components["schemas"]["OrderStatus"];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            actor_type: components["schemas"]["ActorType"];
            actor_ref?: components["schemas"]["WaslaPublicId"] | null;
            /** Format: date-time */
            occurred_at: string;
            trace_id?: string | null;
        };
        Order: {
            /** Format: uuid */
            id: string;
            order_public_id: components["schemas"]["OrderPublicId"];
            /** Format: uuid */
            order_request_id: string;
            customer_public_id: components["schemas"]["WaslaPublicId"];
            order_type: components["schemas"]["OrderType"];
            vehicle_class: components["schemas"]["VehicleClass"];
            status: components["schemas"]["OrderStatus"];
            status_reason_code?: components["schemas"]["ReasonCode"] | null;
            price_mode: components["schemas"]["PriceMode"];
            offered_price?: components["schemas"]["Money"] | null;
            stops: components["schemas"]["Stop"][];
            shipment?: components["schemas"]["ShipmentDetails"] | null;
            notes?: string | null;
            active_assignment?: components["schemas"]["Assignment"] | null;
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            accepted_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ErrorResponse: {
            /** @description كود ثابت (stable) — الاختبارات تتحقّق منه لا من النص */
            code: string;
            message: string;
            trace_id?: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الكيان غير موجود (أو ليس مملوكاً للقارئ) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض حالة (انتقال غير مسموح · إعادة مفتاح بحمولة مختلفة · إسناد مكرَّر) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description صالح شكلياً وغير مقبول منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrderId: string;
        /** @description نطاق القراءة. طلب عميل آخر يُجيب 404 (لا نُثبت وجود ما لا يُقرأ). */
        CustomerScope: components["schemas"]["WaslaPublicId"];
        /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    intakeOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIntakeRequest"];
            };
        };
        responses: {
            /** @description إعادة مفتاح idempotency بنفس الحمولة — نفس النتيجة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderIntakeResult"];
                };
            };
            /** @description أُنشئ الطلب */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderIntakeResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description نطاق القراءة. طلب عميل آخر يُجيب 404 (لا نُثبت وجود ما لا يُقرأ). */
                "X-Customer-Public-Id": components["parameters"]["CustomerScope"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الطلب */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrderHistory: {
        parameters: {
            query?: never;
            header: {
                /** @description نطاق القراءة. طلب عميل آخر يُجيب 404 (لا نُثبت وجود ما لا يُقرأ). */
                "X-Customer-Public-Id": components["parameters"]["CustomerScope"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description التاريخ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["StatusHistoryEntry"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    transitionOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description تمّ الانتقال (أو إعادة نفس المفتاح بنفس الحمولة) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    recordAssignment: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    driver_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description سُجّل العرض */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateAssignmentState: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على كل كتابة (§43). مدخل النظام بوت، وضغط الزر مرّتين حالة عادية. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الرد وفي مغلّف الحدث وفي صفّ التدقيق. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    assignment_state: "accepted" | "rejected" | "expired" | "cancelled";
                    reason_code?: components["schemas"]["ReasonCode"];
                };
            };
        };
        responses: {
            /** @description حُدِّثت الحالة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
}
