/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/channel/{bot}/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * استقبال تحديث من القناة
         * @description يستقبل تحديثاً خاماً من القناة (Telegram Update). لا يُفسَّر جسم الطلب في
         *     العقد لأن شكله ملك القناة — المُهيّئ (Adapter) هو الجهة الوحيدة التي تُفسّره
         *     وتُحوّله إلى `InboundUpdate` محايد. الاستجابة سريعة (202) والمعالجة الثقيلة
         *     لا تحجب القناة.
         */
        post: operations["receiveUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إرسال رسالة صادرة عبر القناة
         * @description نقطة الخروج الوحيدة للرسائل. الطلب يحمل `idempotency_key` إلزامياً:
         *     تكرار نفس المفتاح لا يُرسل الرسالة مرتين ويُرجَع `status: duplicate`.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/{bot}/mini-app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * واصف تشغيل Mini App الخاصة بالبوت
         * @description يُرجع أي Mini App يفتحها هذا البوت. هذا هو العقد الذي يتحقّق منه
         *     Exit Gate للمرحلة 03: كل بوت يفتح تطبيقه الصحيح.
         */
        get: operations["getMiniAppLaunch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/{bot}/deep-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** توليد Deep Link للبوت */
        post: operations["createDeepLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فحص صحة طبقة القنوات */
        get: operations["getChannelHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description اسم القناة. Phase 03 يُنفّذ telegram فقط؛ البقية محجوزة في العقد.
         * @enum {string}
         */
        ChannelName: "telegram" | "web" | "mobile" | "whatsapp";
        /**
         * @description بوتات وصلة الثلاثة
         * @enum {string}
         */
        BotKind: "customer" | "driver" | "partner";
        /**
         * @description تطبيقات Mini App الثلاثة (مقابل كل بوت)
         * @enum {string}
         */
        MiniAppKind: "customer" | "driver" | "partner";
        UpdateAccepted: {
            /**
             * @description accepted = عُولج الآن · duplicate = سبق معالجته (idempotent)
             * @enum {string}
             */
            status: "accepted" | "duplicate";
            channel: components["schemas"]["ChannelName"];
            bot: components["schemas"]["BotKind"];
            /** @description معرّف التحديث كما وردت من القناة (نصّي — لا يُفترض أنه رقم) */
            channel_update_id?: string;
            kind?: components["schemas"]["InboundUpdateKind"];
        };
        /**
         * @description نوع التحديث بعد التحويل إلى الشكل المحايد
         * @enum {string}
         */
        InboundUpdateKind: "command" | "text_message" | "callback" | "contact" | "location" | "group_event" | "unsupported";
        OutboundMessage: {
            channel: components["schemas"]["ChannelName"];
            /**
             * @description معرّف المحادثة في القناة كمرجع opaque (نصّي). طبقة القنوات لا تُخزّن
             *     ربط `chat_ref` ↔ الهوية — الربط ملك خدمة Identity (تغليف الخدمات).
             */
            chat_ref: string;
            /** @enum {string} */
            kind: "text" | "text_with_buttons";
            text?: string;
            buttons?: components["schemas"]["MessageButton"][];
            /**
             * @description غيابه يعني `normal` (اختياري في الطلب — لا قيمة افتراضية مفروضة على العميل)
             * @enum {string}
             */
            priority?: "critical" | "high" | "normal" | "low";
            /** @description مفتاح فريد للرسالة (يمنع الإرسال المزدوج عند إعادة المحاولة) */
            idempotency_key: string;
            trace_id?: string;
        };
        /**
         * @description زر واحد فقط من نوعين. بناء الزر الفعلي (مثل `web_app` في Telegram) مسؤولية
         *     المُهيّئ — الـCore يصرّح بالنية فقط.
         */
        MessageButton: components["schemas"]["MiniAppButton"] | components["schemas"]["DeepLinkButton"];
        MiniAppButton: {
            /** @constant */
            type: "mini_app";
            label: string;
            mini_app: components["schemas"]["MiniAppKind"];
            /** @description مسار داخلي داخل Mini App (يُلحق بعنوانها الأساسي) */
            path?: string;
        };
        DeepLinkButton: {
            /** @constant */
            type: "deep_link";
            label: string;
            action: components["schemas"]["DeepLinkAction"];
            params?: {
                [key: string]: string;
            };
        };
        /**
         * @description أفعال Deep Link المدعومة في Phase 03 (تُوسّع بإضافة فقط)
         * @enum {string}
         */
        DeepLinkAction: "open_app" | "track_order" | "join_support" | "verify_partner";
        DeepLinkRequest: {
            action: components["schemas"]["DeepLinkAction"];
            params?: {
                [key: string]: string;
            };
        };
        DeepLinkResponse: {
            /** @description الرابط الكامل القابل للمشاركة */
            url: string;
            /**
             * @description الحمولة المُرمّزة (base64url) الموضوعة في الرابط. الحد الأقصى 64 حرفاً
             *     (قيد القناة) — تجاوزه يُرجع 422 `CHANNEL_DEEP_LINK_TOO_LONG`.
             */
            payload: string;
            bot: components["schemas"]["BotKind"];
            action: components["schemas"]["DeepLinkAction"];
        };
        MiniAppLaunch: {
            bot: components["schemas"]["BotKind"];
            mini_app: components["schemas"]["MiniAppKind"];
            /** @description عنوان Mini App الأساسي (HTTPS إلزامي في الإنتاج) */
            url: string;
            label: string;
        };
        DeliveryAccepted: {
            /** Format: uuid */
            delivery_id: string;
            /** @enum {string} */
            status: "queued" | "sent" | "duplicate";
            channel: components["schemas"]["ChannelName"];
            chat_ref: string;
            /** @description عدد محاولات الإرسال المسجّلة حتى الآن */
            attempts?: number;
        };
        Error: {
            /** @description كود ثابت من كتالوج errors.md */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description مدخلات غير صالحة */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description secret token غير مطابق */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description البوت أو المورد غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description مدخلات صالحة شكلياً وغير مقبولة منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description تجاوز حدود القناة — يُعاد المحاولة لاحقاً */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description القناة في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description البوت المستهدف */
        Bot: components["schemas"]["BotKind"];
        /**
         * @description الرمز السري المتفق عليه عند تسجيل الـwebhook. أي طلب بدون تطابق تام
         *     يُرفض بـ 401 `CHANNEL_UNAUTHORIZED_WEBHOOK` قبل أي معالجة.
         */
        SecretToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receiveUpdate: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description الرمز السري المتفق عليه عند تسجيل الـwebhook. أي طلب بدون تطابق تام
                 *     يُرفض بـ 401 `CHANNEL_UNAUTHORIZED_WEBHOOK` قبل أي معالجة.
                 */
                "X-Telegram-Bot-Api-Secret-Token": components["parameters"]["SecretToken"];
            };
            path: {
                /** @description البوت المستهدف */
                bot: components["parameters"]["Bot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description تم قبول التحديث (أو تجاهله كمكرر) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateAccepted"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundMessage"];
            };
        };
        responses: {
            /** @description تم قبول الرسالة للإرسال (أو رُصدت كمكررة) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryAccepted"];
                };
            };
            400: components["responses"]["ValidationError"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMiniAppLaunch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description البوت المستهدف */
                bot: components["parameters"]["Bot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description واصف التشغيل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiniAppLaunch"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createDeepLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description البوت المستهدف */
                bot: components["parameters"]["Bot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepLinkRequest"];
            };
        };
        responses: {
            /** @description الرابط المُولّد */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepLinkResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getChannelHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الحالة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        channel: components["schemas"]["ChannelName"];
                    };
                };
            };
        };
    };
}
