/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identity/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * حلّ أو إنشاء مستخدم Wasla من هوية Telegram
         * @description Idempotent حسب `telegram_user_id`. إذا كان المعرّف مرتبطاً بمستخدم موجود،
         *     يُرجَع ذلك المستخدم دون إنشاء جديد. تغيير `telegram_username` لا يُنشئ مستخدمًا جديدًا —
         *     يُسجَّل في Identity History بدل ذلك.
         */
        post: operations["resolveIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/users/{waslaPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة مستخدم Wasla عبر Wasla Public ID */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/users/{waslaPublicId}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** إضافة رابط هوية خارجي للمستخدم (Phone/Telegram جديد/...) */
        post: operations["addIdentityLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/users/{waslaPublicId}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * بدء استرجاع الحساب عبر Wasla Public ID
         * @description Recovery لا يتجاوز الهوية — يبدأ خطوات تحقق وفق مستوى الحساب والمخاطر.
         *     يجب أن تكون وسيلة التحقق مناسبة (لا تعتمد على Telegram كمصدر وحيد).
         */
        post: operations["startRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/users/{waslaPublicId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** سجل تغييرات الهوية (Username/روابط) */
        get: operations["getIdentityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إصدار جلسة مستخدم من بصمة init-data متحقَّق منها
         * @description ADR-069 · CLM-0519 (المرحلة الأولى). يُصدِر جلسةً صادقةً (4 ساعات افتراضياً) من
         *     بصمةِ `init-data` موقَّعةٍ من قناةِ ثقةٍ (Telegram Mini App). **الفاعلُ يُشتقُّ من
         *     المنادي لا من جسمِ الطلبِ** (I-03): `customer-bot` يُصدِرُ جلسةَ `customer` و`driver-bot`
         *     يُصدِرُ جلسةَ `driver` — أيُّ `actor_type` في الجسمِ يُهجَرُ ولا يُقرأُ. تكرارُ نفسِ
         *     البصمةِ ⇒ 409 (`IDENTITY_SESSION_REPLAY`). الرمزُ الصريحُ يُعاد **مرّةً واحدةً
         *     فقط** ولا يُسجَّلُ في أيِّ سجلٍّ (I-13).
         */
        post: operations["issueUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قايضة جلسة صالحة بتأكيد wua1 قصير العمر (≤60s)
         * @description ADR-069 · CLM-0519 (المرحلة الأولى). يُعيدُ تأكيداً `wua1` موقَّعاً بـ Ed25519
         *     يشهدُ أنّ مالكَ هذه الجلسةِ الصالحةِ هو `wasla_public_id`. فاعلُ الجلسةِ يُقارَنُ
         *     بفعلِ المنادي (I-10: `driver-bot` لا يستبدلُ جلسةَ `customer`). الرمزُ المنتهي ⇒ 401
         *     `AUTHN_EXPIRED` (I-07)، المُلغى أو غيرُ المعروف ⇒ 401 `AUTHN_UNAUTHENTICATED`
         *     بنفسِ النصِّ (I-08)، المستخدمُ الموقوفُ ⇒ 403 `IDENTITY_USER_SUSPENDED` (I-11)،
         *     بلا مفتاحِ توقيعٍ ⇒ 503 `IDENTITY_ASSERTION_UNAVAILABLE` (I-12). التأكيدُ لا يُسجَّلُ
         *     ولا يُرسَلُ في أيِّ سجلٍّ (I-13).
         */
        post: operations["exchangeUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * سحب جلسة مستخدم برموزها
         * @description ADR-069 · CLM-0519 (المرحلة الأولى). يُلغِي الجلسةَ المصادَقَ عليها برموزِها —
         *     مُتماثلُ التكرارِ عندَ المستودعِ. سحبُ ما لا وجودَ لهُ ⇒ 404 `IDENTITY_SESSION_NOT_FOUND`
         *     (لأنّ المُنادي يظنُّ حالةً غيرَ الواقعِ). السببُ يُسجَّلُ ولا يُفصَحُ عن رمزِ
         *     الجلسةِ في أيِّ سجلٍّ (I-13).
         */
        post: operations["revokeUserSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/assertions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إصدار تأكيد المستخدم النهائي wua1 لهوية قناة قائمة
         * @description ADR-060 · CLM-0440 · RISK-0042. يُصدِر تأكيداً موقَّعاً بـ Ed25519 (المفتاح الخاص عند identity وحدها)
         *     يشهد أن مستخدم القناة `telegram_user_id` هو `wasla_public_id`. **قراءة فقط**: لا يُنشئ مستخدماً
         *     (مستخدم غير مربوط ⇒ 404). نوع الفاعل يتبع المنادي (customer-bot → customer، driver-bot → driver،
         *     partner-bot → store_staff) والجمهور من قائمة مغلقة لكل فاعل. بلا مفتاح توقيع مُهيّأ ⇒ 503.
         *     البوت يُمرِّر التأكيد في ترويسة `x-wasla-user-assertion` مع `obo` مساوٍ لـ `wasla_public_id`،
         *     ولا يصنعه ولا يعدّله.
         */
        post: operations["issueUserAssertion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResolveIdentityRequest: {
            /**
             * Format: int64
             * @description معرّف Telegram الرقمي (ليس Username) — المفتاح Idempotent
             */
            telegram_user_id: number;
            /** @description Username الحالي (يُسجَّل في History عند التغيير) */
            telegram_username?: string;
            telegram_language_code?: string;
            /**
             * @description مصدر الدخول (لأغراض Audit)
             * @enum {string}
             */
            source?: "customer_bot" | "driver_bot" | "partner_bot";
        };
        IssueUserAssertionRequest: {
            /** Format: int64 */
            telegram_user_id: number;
            /** @enum {string} */
            actor_type: "customer" | "driver" | "store_staff";
            audience: string[];
        };
        /**
         * @description بصمةُ init-data نتيجةُ `fingerprintInitData` في `@wasla/telegram-adapter` —
         *     ليست مفتاحَ منعِ إعادةٍ قابلٍ للصنعِ من أيِّ طلبٍ. `actor_type` إن وُجدَ يُهجَرُ
         *     (I-03: المنبعُ مسارُ الثقةِ).
         */
        IssueSessionRequest: {
            /** Format: int64 */
            telegram_user_id: number;
            /** @description بصمة sha256 لرسالة init-data الموقَّعة */
            init_data_fingerprint: string;
            /** @description يُهجَرُ ولا يُقرأُ — الفاعلُ من مسارِ الثقةِ (ADR-069 §2.6) */
            actor_type?: string;
            telegram_username?: string;
            telegram_first_name?: string;
            telegram_language_code?: string;
        };
        IssueSessionResponse: {
            /** @description الرمز المُعتِم — يُعاد مرّةً واحدةً ولا يُسجَّل */
            token: string;
            wasla_public_id: string;
            /**
             * @description مُشتقٌّ من مسارِ الثقةِ (هويّةِ الخدمةِ المنادية) لا من جسمِ الطلبِ
             * @enum {string}
             */
            actor_type: "customer" | "driver";
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            session_id: string;
        };
        ExchangeSessionRequest: {
            /** @description رمز الجلسة الصادرة من `POST /identity/sessions` */
            session_token: string;
            audience: string[];
        };
        ExchangeSessionResponse: {
            /** @description wua1.<payload>.<sig> — يُمرَّر كما هو ولا يُسجَّل */
            assertion: string;
            wasla_public_id: string;
            /** @enum {string} */
            actor_type: "customer" | "driver";
            audience: string[];
            /**
             * Format: date-time
             * @description انتهاء التأكيد — لا يتجاوز 60 ثانية من الإصدار
             */
            expires_at: string;
        };
        RevokeSessionRequest: {
            session_token: string;
            /** @description سبب السحب (يُسجَّل) — يُفترَض `user_requested` عندَ الفراغِ */
            reason?: string;
        };
        RevokeSessionResponse: {
            revoked: boolean;
            /** Format: uuid */
            session_id: string;
        };
        IssueUserAssertionResponse: {
            /** @description wua1.<payload>.<sig> — يُمرَّر كما هو ولا يُسجَّل */
            assertion: string;
            wasla_public_id: string;
            /** @enum {string} */
            actor_type: "customer" | "driver" | "store_staff";
            audience: string[];
            /** Format: date-time */
            expires_at: string;
        };
        ResolveIdentityResponse: {
            wasla_public_id: string;
            /**
             * Format: uuid
             * @description داخلي فقط — لا يُعرض للمستخدم النهائي
             */
            internal_uuid: string;
            /** @description true إذا أُنشئ مستخدم جديد في هذه العملية */
            created: boolean;
            links?: components["schemas"]["IdentityLink"][];
        };
        User: {
            wasla_public_id: string;
            /** @enum {string} */
            status: "active" | "suspended" | "deleted" | "recovery_in_progress";
            /** Format: date-time */
            created_at: string;
            links?: components["schemas"]["IdentityLink"][];
        };
        IdentityLink: {
            /** @enum {string} */
            provider: "telegram" | "phone" | "email" | "web" | "mobile";
            /** @description المعرّف الخارجي (telegram_user_id / رقم هاتف normalyzed / ...) */
            external_id: string;
            verified?: boolean;
            /** Format: date-time */
            linked_at?: string;
        };
        AddIdentityLinkRequest: {
            /** @enum {string} */
            provider: "telegram" | "phone" | "email" | "web" | "mobile";
            external_id: string;
            verified?: boolean;
        };
        StartRecoveryRequest: {
            /**
             * @description يجب ألا تعتمد على Telegram كمصدر وحيد
             * @enum {string}
             */
            verification_method: "phone_otp" | "email_otp" | "admin_assisted";
        };
        RecoveryStarted: {
            /** Format: uuid */
            recovery_id: string;
            /** @enum {string} */
            status: "verification_pending" | "completed" | "rejected";
        };
        IdentityHistoryEntry: {
            /** @enum {string} */
            field: "telegram_username" | "phone" | "link";
            old_value: string | null;
            new_value: string;
            /** Format: date-time */
            effective_at: string;
            /** @enum {string} */
            source: "customer_bot" | "driver_bot" | "partner_bot" | "recovery" | "admin" | "system";
        };
        Error: {
            /** @description كود خطأ ثابت (راجع errors.md) */
            code: string;
            message: string;
            trace_id?: string;
        };
        ErrorResponse: {
            /** @description كود ثابت (stable) */
            code: string;
            message: string;
            trace_id: string;
        };
    };
    responses: {
        /** @description طلب غير صالح */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description تعارض (مثلاً: الرابط مرتبط بمستخدم آخر) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description المدخلات صالحة شكلياً لكن غير مقبولة منطقياً */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description الخدمة غير متاحة (degraded mode) */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description طلبٌ بلا ترويسةِ هويّةِ خدمةٍ، أو بتوقيعٍ غيرِ صحيحٍ، أو برمزٍ منتهي الصلاحيّةِ أو مُستعمَلٍ ثانيةً. الردُّ لا يُفصِحُ عن السببِ الدقيقِ. */
        AuthUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description هويّةُ خدمةٍ صحيحةٌ ولكنّ الصلاحيّةَ المطلوبةَ غيرُ ممنوحةٍ لهذهِ الخدمةِ، أو المُنتَفِعُ الموقَّعُ في الرمزِ لا يملكُ الموردَ المطلوبَ. */
        AuthForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description رقم الهوية المرئي والدائم (مثال WS-0000010427) */
        WaslaPublicId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolveIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIdentityRequest"];
            };
        };
        responses: {
            /** @description مستخدم موجود تم حلّه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveIdentityResponse"];
                };
            };
            /** @description مستخدم جديد أُنشئ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveIdentityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description رقم الهوية المرئي والدائم (مثال WS-0000010427) */
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المستخدم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    addIdentityLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description رقم الهوية المرئي والدائم (مثال WS-0000010427) */
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddIdentityLinkRequest"];
            };
        };
        responses: {
            /** @description الرابط أُضيف */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityLink"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    startRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description رقم الهوية المرئي والدائم (مثال WS-0000010427) */
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRecoveryRequest"];
            };
        };
        responses: {
            /** @description بدأت خطوات التحقق */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryStarted"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getIdentityHistory: {
        parameters: {
            query?: {
                field?: "telegram_username" | "phone" | "link";
            };
            header?: never;
            path: {
                /** @description رقم الهوية المرئي والدائم (مثال WS-0000010427) */
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description السجل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityHistoryEntry"][];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
        };
    };
    issueUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueSessionRequest"];
            };
        };
        responses: {
            /** @description جلسة صادرة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    exchangeUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeSessionRequest"];
            };
        };
        responses: {
            /** @description تأكيد صادر من جلسة صالحة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeSessionRequest"];
            };
        };
        responses: {
            /** @description الجلسة سُحبت */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResponse"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    issueUserAssertion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueUserAssertionRequest"];
            };
        };
        responses: {
            /** @description تأكيد صادر */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueUserAssertionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthUnauthorized"];
            403: components["responses"]["AuthForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
