/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * صحة الخدمة ووضع تشغيلها
         * @description يُعلن الوضع (`postgres` أو `memory`) صراحةً كي لا يُقرأ اجتيازُ الفحص في وضع الذاكرة دليلاً على
         *     استمراريّةٍ لا وجود لها. ولا `last_tick_at` هنا: لا نبضة في هذه الخدمة (القرار 2).
         */
        get: operations["getMarketplaceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * شجرة التصنيفات
         * @description شجرةٌ بمستويَين: جذورٌ بلا أبٍ وأوراقٌ بأب. والمنتجُ **لا يُصنَّف إلّا على ورقة**
         *     (`PRODUCT_CATEGORY_NOT_LEAF`): تصنيفٌ على جذرٍ يجعل «إلكترونيات» سلّةَ كلِّ ما لم يُصنَّف، ثمّ لا
         *     يعرف أحدٌ ما فيها.
         */
        get: operations["listStoreCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * قراءة المتاجر بترشيح معلن
         * @description **مُرشِّحٌ واحدٌ على الأقلّ إلزامي** (`MARKETPLACE_FILTER_REQUIRED`): قراءةٌ بلا مُرشِّحٍ تصبح
         *     مسحاً كاملاً للجدولِ في أوّلِ لوحةٍ تُبنى عليه. والترقيمُ بمفتاحٍ ثابتٍ (`created_at`,`id`) لا
         *     بإزاحةٍ: الإزاحةُ تُكرِّر صفّاً وتُسقط آخرَ حين يُسجَّل متجرٌ بين صفحتَين.
         */
        get: operations["listStores"];
        put?: never;
        /**
         * تسجيل متجر
         * @description يُنشئ متجراً بحالةِ `draft` لا `pending_review`: التسجيلُ ليس طلبَ مراجعة، وصاحبُ المتجرِ يحتاج
         *     وقتاً ليُكمل بياناته ومنتجاتِه قبل أن يُقرأ نقصُه رفضاً. و`ux_stores_owner_active` يمنع متجراً
         *     نشطاً ثانياً لنفسِ المالك (`STORE_OWNER_LIMIT_REACHED`)، و`ux_stores_slug_lower` يجعل التفرّدَ
         *     غيرَ حسّاسٍ لحالةِ الأحرف — `Wasla` و`wasla` رابطان يقرؤهما الإنسانُ واحداً.
         */
        post: operations["registerStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة متجر واحد */
        get: operations["getStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/review-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * طلب مراجعة المتجر
         * @description `draft → pending_review`، أو `rejected → pending_review` بعد إصلاحِ سببِ الرفض. وطلبٌ ثانٍ وطلبةٌ
         *     قائمةٌ لم تُحسَم يُرفض بـ`STORE_REVIEW_ALREADY_PENDING`: السماحُ به يُنتج طابوراً فيه صفوفٌ لنفسِ
         *     المتجرِ يتنازعها مُراجعان.
         */
        post: operations["requestStoreReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قرار اعتدال على متجر
         * @description مسارٌ واحدٌ لكلِّ القرارات (`approved`,`rejected`,`suspended`,`reinstated`,`archived`) لا مسارٌ
         *     لكلِّ فعل: القرارُ صفٌّ في دفترٍ واحدٍ بجدولِ انتقالاتٍ واحد، ومسارٌ منفصلٌ لكلِّ فعلٍ يُنتج خمسَ
         *     نسخٍ من التحقّقِ نفسِه تنحرف واحدةً واحدة. والانتقالُ غيرُ المسموحِ يُرفض بـ
         *     `STORE_DECISION_NOT_ALLOWED`، والرفضُ والإيقافُ بلا سببٍ من القائمةِ المغلقةِ بـ
         *     `STORE_REJECTION_REASON_REQUIRED`.
         */
        post: operations["decideStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * دفتر قرارات المتجر
         * @description الدفترُ كما كُتب بترتيبِ `state_sequence`. وهذا هو المسارُ الذي يجعل إسقاطَ `stores.state`
         *     وإعادةَ بنائه ممكناً، وهو الدليلُ على أنّ الحالةَ إسقاطٌ لا مصدرُ حقيقة.
         */
        get: operations["listStoreReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** طاقم المتجر */
        get: operations["listStoreStaff"];
        put?: never;
        /**
         * إضافة عضو إلى الطاقم
         * @description الأدوارُ قائمةٌ مغلقة `owner|manager|staff`، و`ux_store_staff_single_owner` يجعل المالكَ واحداً في
         *     القاعدةِ لا في الكود. وعضويّةٌ نشطةٌ قائمةٌ لنفسِ الشخصِ تُرفض بـ`STORE_STAFF_ALREADY_MEMBER` لا
         *     تُحدَّث بدورٍ جديد: تغييرُ الدورِ في موضعِه يمحو أنّه كان `staff` يومَ وقع ما وقع.
         */
        post: operations["addStoreStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/staff/{memberPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * إزالة عضو من الطاقم
         * @description تُكتب `removed_at` ولا يُحذف صفّ (القرار 9). ودورُ المالكِ لا يُزال
         *     (`STORE_OWNER_ROLE_IMMUTABLE`): متجرٌ بلا مالكٍ متجرٌ لا يُسأل أحدٌ عن محتواه. والجوابُ `200` لا
         *     `204` لأنّ المستهلكَ يحتاج `removed_at` كما سُجِّل لا فراغاً يستنتج منه النجاح.
         */
        delete: operations["removeStoreStaff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{storeSlug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * منتجات المتجر
         * @description **لا `?q=` هنا**: البحثُ ملكُ الطور 12 (القرار 9)، والترشيحُ بمفاتيحَ معلنةٍ لا بمطابقةِ نصٍّ حرّ.
         *     و`visible_only` يُحسَب عند القراءةِ من الشروطِ الأربعةِ ولا يُقرأ من عمود (القرار 3).
         */
        get: operations["listStoreProducts"];
        put?: never;
        /**
         * إنشاء منتج
         * @description يُنشأ المنتجُ `draft` واعتدالُه `pending`، ويُقبَل الإنشاءُ **في متجرٍ مُعتمَدٍ فقط**
         *     (`STORE_NOT_APPROVED`): كتالوجٌ يُبنى في متجرٍ لم يُعتمَد يُنتج طابورَ اعتدالٍ لمنتجاتٍ قد لا يُعتمَد
         *     متجرُها أبداً. و`ux_products_store_sku` يجعل `sku` فريداً داخلَ المتجرِ لا عبرَ المنصّة: رقمُ
         *     الصنفِ مفتاحُ صاحبِ المتجرِ في نظامِه هو، وحجزُه عالميّاً يمنع متجرَين مستقلَّين من استعمال `A-1`.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قراءة منتج */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * نشر منتج
         * @description `draft → published` بقرارِ المتجرِ لا بقرارِ الاعتدال. ولا يقع إلّا إذا كان الاعتدالُ `approved`
         *     (`PRODUCT_NOT_MODERATED`)، والقيدُ `ck_products_published_moderated` يجعل غيرَه مستحيلاً في
         *     القاعدةِ لا مرجوّاً في الكود. والنشرُ **ليس ظهوراً**: قد يُنشَر المنتجُ ولا يَظهر لأنّ كميّتَه صفرٌ
         *     أو متجرَه مُوقَف، ولذلك يُعاد `is_visible` المُشتَقُّ في الجوابِ كي لا يُبلَّغ صاحبُ المتجرِ بما ليس
         *     حقّاً.
         */
        post: operations["publishProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * أرشفة منتج
         * @description نهايةٌ لا رجوعَ منها (`PRODUCT_TRANSITION_NOT_ALLOWED` لأيِّ انتقالٍ بعدها). والأرشفةُ **تُصفّر
         *     المخزونَ بفرقٍ مُسمّىً** `archive_zeroed` في المعاملةِ نفسِها لا بكتابةِ صفرٍ في الرصيد: لو كُتب
         *     الصفرُ مباشرةً لانحرف الرصيدُ عن دفترِه، ولصار حارسُ الانحرافِ يشتكي من عمليّةٍ صحيحةٍ فيُعلَّم
         *     أحدُهم أن يتجاهله.
         */
        post: operations["archiveProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * قرار اعتدال على منتج
         * @description `approved` أو `rejected` بسببٍ من قائمةٍ مغلقة. والاعتمادُ **إذنٌ لا فِعل**: لا يَنشُر المنتجَ،
         *     والنشرُ قرارُ المتجرِ في مسارٍ آخر. ودمجُهما كان سيجعل مُراجعاً ينشر باسمِ متجرٍ لم يقرّر أنّ
         *     منتجَه صار جاهزاً للعرض.
         */
        post: operations["decideProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * رصيد المخزون ودفتره
         * @description يُعاد الإسقاطُ (`quantity_on_hand`) ودفترُ فروقِه معاً كي يكون الانحرافُ مرئيّاً للقارئِ لا
         *     مكتشَفاً في حادثة. ولا `quantity_reserved` ولا `quantity_available`: الحجزُ ملكُ الطور 13
         *     (القرار 5).
         */
        get: operations["getProductInventory"];
        put?: never;
        /**
         * تسجيل فرق مخزون
         * @description الطلبُ **فرقٌ لا رصيدٌ جديد**: `quantity_delta` صحيحٌ غيرُ صفريٍّ بسببٍ من قائمةٍ مغلقة. وضبطُ
         *     الرصيدِ مباشرةً (`PUT quantity = 7`) كان أبسطَ نداءً وأسوأَ عقداً: طلبان متوازيان من موظّفَين
         *     يُنتجان رصيداً يعتمد على من وصل ثانياً بلا أثرٍ لما فُقد، أمّا الفروقُ فتتراكم كلُّها ويحكيها
         *     دفترُها. وفرقٌ يُنزل الرصيدَ تحت الصفرِ يُرفض بـ`INVENTORY_INSUFFICIENT_QUANTITY`.
         */
        post: operations["adjustProductInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque للمالك أو العضو أو الفاعل؛ لا يُحلَّل ولا يعبر حدَّ الخدمةِ كعلاقةِ قاعدةِ بيانات. */
        WaslaPublicId: string;
        StoreSlug: string;
        CategorySlug: string;
        /**
         * @description صفٌ متحقّقٌ مُشتَقٌّ من `store_reviews`، وإسقاطُه لا يفقد شيئاً. `archived` نهايةٌ لا رجوعَ منها.
         * @enum {string}
         */
        StoreState: "draft" | "pending_review" | "approved" | "rejected" | "suspended" | "archived";
        /** @enum {string} */
        StoreDecision: "review_requested" | "approved" | "rejected" | "suspended" | "reinstated" | "archived";
        /** @enum {string} */
        StoreReasonCode: "incomplete_profile" | "prohibited_category" | "duplicate_store" | "misleading_title" | "unverified_owner" | "policy_violation" | "owner_request";
        /** @enum {string} */
        ProductState: "draft" | "published" | "archived";
        /** @enum {string} */
        ProductModerationState: "pending" | "approved" | "rejected";
        /** @enum {string} */
        ProductDecision: "approved" | "rejected";
        /** @enum {string} */
        ProductReasonCode: "prohibited_item" | "misleading_title" | "wrong_category" | "price_implausible" | "duplicate_listing" | "policy_violation";
        /** @enum {string} */
        InventoryReasonCode: "initial_stock" | "restock" | "correction" | "shrinkage" | "archive_zeroed";
        StoreCategory: {
            category_slug: components["schemas"]["CategorySlug"];
            label_ar: string;
            label_en?: string | null;
            label_ur?: string | null;
            /**
             * @description مستويان لا شجرةٌ مفتوحة: `1` جذرٌ للتصفّحِ و`2` ورقةٌ للتصنيف. والمنتجُ يُصنَّف على
             *     ورقةٍ فقط (`PRODUCT_CATEGORY_NOT_LEAF`)، فلا حاجةَ إلى `is_leaf` عموداً ثانياً لحقيقةٍ
             *     يقولها `depth` — عمودان لمعنىً واحدٍ ينحرفان.
             * @enum {integer}
             */
            depth: 1 | 2;
            /** @description `null` تعني جذراً لا تصنيفاً بلا أب مجهولاً؛ والقيدُ `ck_store_categories_depth_parent` يربطها بـ`depth`. */
            parent_slug: components["schemas"]["CategorySlug"] | null;
            sort_order: number;
            is_active: boolean;
        };
        RegisterStoreRequest: {
            owner_public_id: components["schemas"]["WaslaPublicId"];
            store_slug: components["schemas"]["StoreSlug"];
            title_ar: string;
            title_en?: string | null;
            title_ur?: string | null;
            description_ar?: string | null;
            category_slug: components["schemas"]["CategorySlug"];
        };
        StoreResource: {
            /** Format: uuid */
            store_id: string;
            store_slug: components["schemas"]["StoreSlug"];
            owner_public_id: components["schemas"]["WaslaPublicId"];
            title_ar: string;
            title_en?: string | null;
            title_ur?: string | null;
            description_ar?: string | null;
            category_slug: components["schemas"]["CategorySlug"];
            state: components["schemas"]["StoreState"];
            /** @description تسلسلُ آخرِ قرارٍ دخل الدفتر؛ يبدأ من 1 عند الإنشاء لا من صفر — تسلسلٌ صفريٌّ كان سيجعل «لا قرارَ بعد» و«القرارُ الأوّل» قيمتين متجاورتين يُخطئ بينهما كلُّ مقارَنة. */
            state_sequence: number;
            /** @description مُشتَقٌّ من `first_approved_at` لا عمودٌ مستقل؛ عمودان لحقيقةٍ واحدةٍ ينحرفان. */
            is_slug_locked: boolean;
            /** Format: date-time */
            first_approved_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        StoreDecisionRequest: {
            decision: components["schemas"]["StoreDecision"];
            /**
             * @description `system` وحدَه يُسمَح له بغيابِ `actor_public_id`؛ قرارٌ بلا فاعلٍ مُسمّىً قرارٌ لا يُسأل عنه أحد.
             * @enum {string}
             */
            actor_type: "owner" | "moderator" | "system";
            actor_public_id?: components["schemas"]["WaslaPublicId"] | null;
            reason_code?: components["schemas"]["StoreReasonCode"] | null;
        };
        StoreReviewResource: {
            /** Format: uuid */
            review_id: string;
            /** Format: uuid */
            store_id: string;
            store_slug: components["schemas"]["StoreSlug"];
            decision: components["schemas"]["StoreDecision"];
            from_state: components["schemas"]["StoreState"] | null;
            to_state: components["schemas"]["StoreState"];
            state_sequence: number;
            /** @enum {string} */
            actor_type: "owner" | "moderator" | "system";
            actor_public_id?: components["schemas"]["WaslaPublicId"] | null;
            reason_code?: components["schemas"]["StoreReasonCode"] | null;
            /** Format: date-time */
            decided_at: string;
        };
        StoreStaffResource: {
            /** Format: uuid */
            staff_id: string;
            /** Format: uuid */
            store_id: string;
            member_public_id: components["schemas"]["WaslaPublicId"];
            /** @enum {string} */
            role: "owner" | "manager" | "staff";
            added_by_public_id: components["schemas"]["WaslaPublicId"];
            /** Format: date-time */
            added_at: string;
            /**
             * Format: date-time
             * @description `null` تعني عضويّةً نشطة؛ الإزالةُ كتابةُ زمنٍ لا حذفُ صفّ.
             */
            removed_at: string | null;
            removed_by_public_id?: components["schemas"]["WaslaPublicId"] | null;
        };
        CreateProductRequest: {
            sku: string;
            title_ar: string;
            title_en?: string | null;
            title_ur?: string | null;
            description_ar?: string | null;
            category_slug: components["schemas"]["CategorySlug"];
            /**
             * @description بالهللات وعددٌ صحيحٌ حصراً. لا `NUMERIC` ولا `FLOAT`: كسرٌ عائمٌ في سعرٍ يُجمَع مرّتَين يُنتج
             *     فرقاً لا يُفسَّر لأحد. وهذا **بيانُ كتالوجٍ لا حركةُ مال** (القرار 4).
             */
            price_minor_units: number;
            /**
             * @description قيمةٌ واحدةٌ اليوم؛ عمودٌ بلا قيدٍ كان سيوهم بدعمِ عملاتٍ لا يملك الطورُ تحويلَها.
             * @constant
             */
            currency_code: "SAR";
            /** @description عند تجاوزِه الصفرَ يُسجَّل فرقٌ بسببِ `initial_stock` في المعاملةِ نفسِها؛ لا كتابةَ رصيدٍ بلا دفتر. */
            initial_quantity?: number;
            created_by_public_id: components["schemas"]["WaslaPublicId"];
        };
        ProductResource: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            store_id: string;
            store_slug: components["schemas"]["StoreSlug"];
            sku: string;
            title_ar: string;
            title_en?: string | null;
            title_ur?: string | null;
            description_ar?: string | null;
            category_slug: components["schemas"]["CategorySlug"];
            price_minor_units: number;
            /** @constant */
            currency_code: "SAR";
            state: components["schemas"]["ProductState"];
            moderation_state: components["schemas"]["ProductModerationState"];
            moderation_sequence: number;
            /** @description إسقاطُ دفترِ الفروق؛ يجب أن يطابق مجموعَه. */
            quantity_on_hand: number;
            /**
             * @description **مُحسوبٌ عند القراءةِ لا مُخزَّنٌ في عمود** (القرار 3): المتجرُ `approved` ∧ المنتجُ
             *     `published` ∧ الاعتدالُ `approved` ∧ `quantity_on_hand > 0`.
             */
            is_visible: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductDecisionRequest: {
            decision: components["schemas"]["ProductDecision"];
            /** @enum {string} */
            actor_type: "moderator" | "system";
            actor_public_id?: components["schemas"]["WaslaPublicId"] | null;
            reason_code?: components["schemas"]["ProductReasonCode"] | null;
        };
        ProductReviewResource: {
            /** Format: uuid */
            review_id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            store_id: string;
            decision: components["schemas"]["ProductDecision"];
            from_state: components["schemas"]["ProductModerationState"] | null;
            to_state: components["schemas"]["ProductModerationState"];
            moderation_sequence: number;
            /** @enum {string} */
            actor_type: "moderator" | "system";
            actor_public_id?: components["schemas"]["WaslaPublicId"] | null;
            reason_code?: components["schemas"]["ProductReasonCode"] | null;
            /** Format: date-time */
            decided_at: string;
        };
        AdjustInventoryRequest: {
            /** @description فرقٌ موقّعٌ غيرُ صفريّ. فرقٌ صفريٌّ ليس حدثاً؛ قبولُه يُنتج دفتراً فيه صفوفٌ لا تعني شيئاً. */
            quantity_delta: number;
            reason_code: components["schemas"]["InventoryReasonCode"];
            actor_public_id: components["schemas"]["WaslaPublicId"];
        };
        InventoryAdjustmentResource: {
            /** Format: uuid */
            adjustment_id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            store_id: string;
            quantity_delta: number;
            quantity_after: number;
            reason_code: components["schemas"]["InventoryReasonCode"];
            adjustment_sequence: number;
            actor_public_id: components["schemas"]["WaslaPublicId"];
            /** Format: date-time */
            occurred_at: string;
        };
        InventoryReadResponse: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            store_id: string;
            quantity_on_hand: number;
            last_adjustment_sequence: number;
            /** @description فارغةٌ حين لا يُطلب الدفتر؛ الفراغُ ليس غياباً للدفترِ بل عدمَ طلبٍ له. */
            adjustments: components["schemas"]["InventoryAdjustmentResource"][];
            next_cursor: string | null;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            /** @enum {string} */
            mode: "postgres" | "memory";
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "MARKETPLACE_VALIDATION_FAILED" | "MARKETPLACE_IDEMPOTENCY_KEY_REQUIRED" | "MARKETPLACE_FILTER_REQUIRED" | "STORE_NOT_FOUND" | "PRODUCT_NOT_FOUND" | "STORE_CATEGORY_NOT_FOUND" | "STORE_STAFF_NOT_FOUND" | "MARKETPLACE_IDEMPOTENCY_KEY_REUSED" | "STORE_SLUG_TAKEN" | "STORE_OWNER_LIMIT_REACHED" | "PRODUCT_SKU_TAKEN" | "STORE_STAFF_ALREADY_MEMBER" | "STORE_REVIEW_ALREADY_PENDING" | "STORE_DECISION_NOT_ALLOWED" | "PRODUCT_TRANSITION_NOT_ALLOWED" | "STORE_SLUG_RESERVED" | "STORE_NOT_APPROVED" | "PRODUCT_NOT_MODERATED" | "STORE_CATEGORY_INACTIVE" | "PRODUCT_CATEGORY_NOT_LEAF" | "STORE_OWNER_ROLE_IMMUTABLE" | "INVENTORY_INSUFFICIENT_QUANTITY" | "STORE_REJECTION_REASON_REQUIRED" | "MARKETPLACE_UNAVAILABLE";
                message: string;
                /**
                 * @description تفاصيلُ بنيويّةٌ بلا إعادةِ قيمةِ المدخل. الحقولُ معدودةٌ لا حقيبةٌ حرّة؛ فتحُها بلا عقدٍ
                 *     يجعل المستهلكَ الصارمَ يفشل عند أوّلِ مفتاحٍ جديدٍ في استجابةٍ صحيحة.
                 */
                details?: {
                    /** @description اسم الحقل المرفوض لا قيمته. */
                    field?: string;
                    /** @description شكلٌ متوقّعٌ أو قاعدةٌ معلنة. */
                    expected?: string;
                    store_slug?: components["schemas"]["StoreSlug"];
                    /** Format: uuid */
                    product_id?: string;
                    category_slug?: components["schemas"]["CategorySlug"];
                    member_public_id?: components["schemas"]["WaslaPublicId"];
                    from_state?: string;
                    to_state?: string;
                    quantity_on_hand?: number;
                    /** @description اسم القيد الذي يحمي الحقيقة نفسها عند تزامن الكتابة. */
                    constraint?: string;
                };
            };
            trace_id: string;
        };
    };
    responses: {
        /** @description مدخلاتٌ غيرُ صالحةٍ شكليّاً أو مفتاحُ تفرّدٍ مفقودٌ أو مُرشِّحُ قراءةٍ ناقص */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description متجرٌ أو منتجٌ أو تصنيفٌ أو عضوُ طاقمٍ غيرُ موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مفتاحُ تفرّدٍ أُعيد مع طلبٍ مختلف، أو تنازعٌ على تفرّدٍ معلن، أو انتقالٌ غيرُ مسموح */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخلٌ صالحٌ شكليّاً ومرفوضٌ بقاعدةِ حالةٍ أو اعتدالٍ أو تصنيفٍ أو مخزون */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمةُ أو طبقةُ الاستمراريةِ غيرُ متاحة */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
        StoreSlug: components["schemas"]["StoreSlug"];
        ProductId: string;
        /** @description مُعرّف العضو العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
        MemberPublicId: components["schemas"]["WaslaPublicId"];
        /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
        IdempotencyKey: string;
        /** @description مؤشّرُ ترقيمٍ مُعادٌ من صفحةٍ سابقة؛ لا يُبنى في المستهلك ولا يُفكَّك. */
        Cursor: string;
        /** @description سقفُ الصفحة؛ الافتراضُ 50 والأقصى 200 كي لا تصبح قراءةٌ واحدةٌ مسحاً للجدول. */
        Limit: number;
        /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMarketplaceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخدمة تستجيب */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStoreCategories: {
        parameters: {
            query?: {
                /** @description عند `true` لا تظهر التصنيفاتُ المُعطَّلةُ التي لا تصلح لتسجيلٍ جديد. */
                active_only?: boolean;
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description التصنيفات المطابقة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        categories: components["schemas"]["StoreCategory"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStores: {
        parameters: {
            query?: {
                state?: components["schemas"]["StoreState"];
                owner_public_id?: components["schemas"]["WaslaPublicId"];
                category_slug?: components["schemas"]["CategorySlug"];
                /** @description مؤشّرُ ترقيمٍ مُعادٌ من صفحةٍ سابقة؛ لا يُبنى في المستهلك ولا يُفكَّك. */
                cursor?: components["parameters"]["Cursor"];
                /** @description سقفُ الصفحة؛ الافتراضُ 50 والأقصى 200 كي لا تصبح قراءةٌ واحدةٌ مسحاً للجدول. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المتاجر المطابقة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        stores: components["schemas"]["StoreResource"][];
                        /** @description `null` تعني نهايةَ النتيجةِ لا خطأً. */
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    registerStore: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStoreRequest"];
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ ولا يُنشأ متجرٌ ثانٍ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResource"];
                };
            };
            /** @description أُنشئ المتجر */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المتجر */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    requestStoreReview: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    requested_by_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreReviewResource"];
                };
            };
            /** @description سُجّل طلبُ المراجعة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreReviewResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    decideStore: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreDecisionRequest"];
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ ولا يُسجَّل قرارٌ ثانٍ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreReviewResource"];
                };
            };
            /** @description دخل القرارُ الدفترَ وتحدّثت الحالةُ المتحقّقة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreReviewResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStoreReviews: {
        parameters: {
            query?: {
                /** @description مؤشّرُ ترقيمٍ مُعادٌ من صفحةٍ سابقة؛ لا يُبنى في المستهلك ولا يُفكَّك. */
                cursor?: components["parameters"]["Cursor"];
                /** @description سقفُ الصفحة؛ الافتراضُ 50 والأقصى 200 كي لا تصبح قراءةٌ واحدةٌ مسحاً للجدول. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description القرارات المسجّلة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reviews: components["schemas"]["StoreReviewResource"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStoreStaff: {
        parameters: {
            query?: {
                /** @description عند `true` لا تظهر العضويّاتُ التي كُتب لها `removed_at`. */
                active_only?: boolean;
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description أعضاء الطاقم */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        staff: components["schemas"]["StoreStaffResource"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    addStoreStaff: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    member_public_id: components["schemas"]["WaslaPublicId"];
                    /** @enum {string} */
                    role: "manager" | "staff";
                    added_by_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreStaffResource"];
                };
            };
            /** @description أُضيف العضو */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreStaffResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    removeStoreStaff: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
                /** @description مُعرّف العضو العام opaque؛ لا يربط هذا العقد مباشرة بقاعدة هوية أخرى. */
                memberPublicId: components["parameters"]["MemberPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    removed_by_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description أُزيلت العضويّة، ويُعاد الصفُّ بـ`removed_at` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreStaffResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listStoreProducts: {
        parameters: {
            query?: {
                state?: components["schemas"]["ProductState"];
                moderation_state?: components["schemas"]["ProductModerationState"];
                /** @description عند `true` تُعاد المنتجاتُ التي تحقّق فيها الاقترانُ الرباعيُّ لحظةَ القراءة. */
                visible_only?: boolean;
                /** @description مؤشّرُ ترقيمٍ مُعادٌ من صفحةٍ سابقة؛ لا يُبنى في المستهلك ولا يُفكَّك. */
                cursor?: components["parameters"]["Cursor"];
                /** @description سقفُ الصفحة؛ الافتراضُ 50 والأقصى 200 كي لا تصبح قراءةٌ واحدةٌ مسحاً للجدول. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المنتجات المطابقة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products: components["schemas"]["ProductResource"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                /** @description مُعرّف المتجر في الرابط؛ فريدٌ بلا حساسيةٍ لحالةِ الأحرفِ ومُقفَلٌ بعد أوّلِ اعتماد. */
                storeSlug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResource"];
                };
            };
            /** @description أُنشئ المنتج */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المنتج */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    publishProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description نُشِر المنتج، أو أُعيد الجوابُ المحفوظ لنفسِ مفتاحِ التفرّد */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    archiveProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor_public_id: components["schemas"]["WaslaPublicId"];
                };
            };
        };
        responses: {
            /** @description أُرشِف المنتجُ وصُفِّر مخزونُه بفرقٍ مُسجَّل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    decideProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductDecisionRequest"];
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReviewResource"];
                };
            };
            /** @description دخل القرارُ الدفترَ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductReviewResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getProductInventory: {
        parameters: {
            query?: {
                /** @description عند `true` يُعاد دفترُ الفروقِ إلى حدِّ `limit`. */
                include_ledger?: boolean;
                /** @description مؤشّرُ ترقيمٍ مُعادٌ من صفحةٍ سابقة؛ لا يُبنى في المستهلك ولا يُفكَّك. */
                cursor?: components["parameters"]["Cursor"];
                /** @description سقفُ الصفحة؛ الافتراضُ 50 والأقصى 200 كي لا تصبح قراءةٌ واحدةٌ مسحاً للجدول. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الرصيد ودفترُه */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryReadResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    adjustProductInventory: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي لكل فعل يغير دفتراً أو إسقاطاً؛ إعادةُ المحاولةِ تعيد جواباً محفوظاً ولا تُنشئ قراراً أو فرقاً ثانياً. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصلُ التتبّعِ عن حمولةِ العملِ يمنع خلطَ المُعرّفِ التشغيليِّ ببياناتِ المجال. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustInventoryRequest"];
            };
        };
        responses: {
            /** @description إعادةُ محاولةٍ بنفس مفتاح التفرّد؛ يُعاد الجوابُ المحفوظ ولا يُخصَم فرقٌ ثانٍ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryAdjustmentResource"];
                };
            };
            /** @description دخل الفرقُ الدفترَ وتحدّث الإسقاط */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryAdjustmentResource"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
