/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * تسجيل ملف دور سائق
         * @description إنشاء ملف دور لا إنشاء هوية. تكرار `Idempotency-Key` بالحمولة نفسها يعيد الملف نفسه بـ`200`؛
         *     لأن إعادة إرسال طلب التسجيل بعد انقطاع الشبكة حالة عادية لا سبب لإنشاء دورين.
         */
        post: operations["registerDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/eligibility/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * نبضة إعادة فحص انتهاء الوثائق
         * @description تقرأ النبضة الاستحقاقات المخزّنة وتعيد حساب الأهليّة ثم تحاول نشر ما تغيّر إلى المطابقة.
         *     لا `requestBody` هنا عمداً: النبضة فعل على الساعة والحالة المخزنة، وإعلان جسم فارغ يجعل Fastify
         *     يرفض طلباً صحيحاً بـ`400`.
         */
        post: operations["tickDriverEligibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ملف سائق واحد */
        get: operations["getDriver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * تعديل حقول الملف القابلة للتغيير
         * @description هذا تعديل ضيّق للحقول التي يملكها الملف. لا يحمل حالة الإيقاف أو التحقق أو الأهليّة، لأن إدخالها
         *     في نفس الجسم يسمح لعميل عادي أن يكتب نتيجة قرار إداري أو قرار مشتق.
         */
        patch: operations["patchDriver"];
        trace?: never;
    };
    "/drivers/{waslaPublicId}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مناطق الخدمة مرتّبة بالتفضيل */
        get: operations["listDriverZones"];
        /**
         * استبدال مناطق الخدمة مرتّبة بالتفضيل
         * @description استبدال كامل لا دمج جزئي: ترتيب قديم مع قائمة جديدة خليط لا يقصده أحد. الرتب تبدأ من `1` وتبقى
         *     متتابعة وفريدة؛ لذلك يحمل الجسم القائمة المقصودة كلها بدلاً من أمر نقل مبهم.
         */
        put: operations["replaceDriverZones"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مركبات السائق */
        get: operations["listDriverVehicles"];
        put?: never;
        /** إضافة مركبة */
        post: operations["registerDriverVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * تعديل حالة المركبة أو أولويتها
         * @description التقاعد وإسناد الرئيسية يمران من عملية واحدة لأن القاعدة تمنع مركبة متقاعدة رئيسية. الفصل بينهما
         *     يجبر العميل على اختيار ترتيب وسيط قد يخرق القيد بلا أن يكون قصده تغييراً تشغيلياً.
         */
        patch: operations["patchDriverVehicle"];
        trace?: never;
    };
    "/drivers/{waslaPublicId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** وثائق السائق */
        get: operations["listDriverDocuments"];
        put?: never;
        /**
         * تقديم مرجع وثيقة
         * @description يقدم المُنادي مرجع التخزين لا الملف ولا بياناته الحساسة. استبدال وثيقة قائمة يبقي السابقة
         *     للتدقيق بدلاً من حذف تاريخ القرار.
         */
        post: operations["submitDriverDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/documents/{documentId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * البت في وثيقة مقدّمة
         * @description قرار المراجعة نهائي للوثيقة نفسها؛ الطلب الثاني لا يغيّر تاريخ القرار. الرفض يحتاج كود سبب كي
         *     يستطيع السائق أن يصلح النقص، أما نص حر فيصير سياسة مختلفة في كل مراجعة.
         */
        post: operations["reviewDriverDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * إعلان التوافر
         * @description `busy` غير مقبول هنا لأنه أثر التزام جارٍ يملكه التوزيع. قبول السائق لكلمة `busy` يجعل
         *     الإعلان يتنافس مع الحقيقة التشغيلية ويخفي من صاحب القرار عند الاختلاف.
         */
        put: operations["updateDriverAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إيقاف السائق
         * @description الإيقاف قرار إداري صريح له سبب؛ لا يُستبدل بتغيير حالة التحقق حتى لا يضيع الفرق بين «وثائقه
         *     ناقصة» و«موقوف». إيقاف موقوف أصلاً تعارض حالة لا عملية ناجحة صامتة.
         */
        post: operations["suspendDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * إعادة سائق موقوف
         * @description لا يحمل الطلب جسماً لأن إعادة الإيقاف تزيل قراراً قائماً ولا تقبل سبباً بديلاً. السائق النشط
         *     ليس حالة يمكن «إعادتها»، لذلك يجيب تعارضاً بدلاً من إخفاء خطأ المشغّل.
         */
        post: operations["reinstateDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{waslaPublicId}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * الأهليّة الحالية وسببها
         * @description يعيد النتيجة المشتقة مع أكواد أسبابها ونسخة السياسة ووقت التقييم؛ الحالة وحدها لا تفسر
         *     القرار، ولا تكفي لتدقيقه بعد أن تتغير السياسة.
         */
        get: operations["getDriverEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * فحص جاهزية الخدمة
         * @description `memory` يجعل النتيجة `degraded` في التشغيل الحقيقي لأن إعادة التشغيل تفقد الدليل الذي يفسر
         *     قرار الأهلية والنشر؛ إظهار الطبقة يميّز المشكلة قبل أن تصبح فقداناً صامتاً للسجل.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description مُعرّف عام opaque؛ لا يُحلّل ولا يربط مباشرة بقاعدة هوية أخرى. */
        WaslaPublicId: string;
        /**
         * Format: uuid
         * @description مرجع opaque إلى هرم الجغرافيا؛ وجوده ونشاطه يقرره منفذ الجغرافيا لا FK عابر للخدمات.
         */
        ZoneRef: string;
        DriverProfile: {
            wasla_public_id: components["schemas"]["WaslaPublicId"];
            display_name?: string | null;
            /** @enum {string} */
            preferred_locale: "ar" | "en" | "ur";
            work_city_zone_id?: components["schemas"]["ZoneRef"] | null;
            /** @description القائمة مقفلة ومشتركة مع الطلب والمطابقة؛ قيمة حرة تصنع خدمة لا يطابقها أحد. */
            service_kinds: ("ride" | "delivery")[];
            /** @enum {string} */
            declared_availability: "available" | "offline";
            /** @enum {string} */
            verification_status: "unverified" | "pending_review" | "verified" | "rejected";
            /** @enum {string} */
            status: "active" | "suspended";
            suspension_reason_code?: string | null;
            eligibility_policy_version: number;
            /** Format: date-time */
            eligibility_recheck_at?: string | null;
            /** @enum {string|null} */
            last_published_state?: "eligible" | "ineligible" | "suspended" | "unknown" | null;
            /** Format: date-time */
            last_published_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DriverRegistration: {
            wasla_public_id: components["schemas"]["WaslaPublicId"];
            display_name?: string | null;
            /**
             * @default ar
             * @enum {string}
             */
            preferred_locale: "ar" | "en" | "ur";
            work_city_zone_id?: components["schemas"]["ZoneRef"] | null;
            /** @default [] */
            service_kinds: ("ride" | "delivery")[];
        };
        DriverProfilePatch: {
            display_name?: string | null;
            /** @enum {string} */
            preferred_locale?: "ar" | "en" | "ur";
            work_city_zone_id?: components["schemas"]["ZoneRef"] | null;
            service_kinds?: ("ride" | "delivery")[];
        };
        ServiceZone: {
            zone_id: components["schemas"]["ZoneRef"];
            preference_rank: number;
            /** Format: date-time */
            created_at: string;
        };
        ServiceZoneList: {
            /** @description مرتبة من الرتبة الأولى إلى الأخيرة؛ تتابع الرتب قيد تجاري تتحقق منه الخدمة. */
            zones: components["schemas"]["ServiceZone"][];
        };
        Vehicle: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            vehicle_class: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
            make?: string | null;
            model?: string | null;
            model_year?: number | null;
            color?: string | null;
            plate_number?: string | null;
            is_primary: boolean;
            /** @enum {string} */
            status: "active" | "retired";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VehicleRegistration: {
            /** @enum {string} */
            vehicle_class: "sedan" | "suv" | "van" | "pickup" | "motorcycle" | "truck_small";
            make?: string | null;
            model?: string | null;
            model_year?: number | null;
            color?: string | null;
            plate_number?: string | null;
            /** @default false */
            is_primary: boolean;
        };
        VehiclePatch: {
            /**
             * @description `retired` وحدها. حُذفت `active` في Phase 05 · MR 4/6 لأنها كانت **وعداً لا يُنجزه أحد**:
             *     `patchVehicle` ترفضها بـ400 منذ MR 2/6 لأن إعادة التفعيل تسجيل جديد لا تعديل — مركبة
             *     خرجت من الخدمة تحتاج أن تُنطر أوراقها من جديد لا أن تُحيا بحرف واحد. إبقاء القيمة
             *     في العقد يدفع المستهلك لكتابة فرع لا ينجح أبداً، وهو أغلى من تضييق قيمة لم تعمل يوماً.
             * @enum {string}
             */
            status?: "retired";
            is_primary?: boolean;
        };
        DriverDocument: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            document_type: "national_id" | "driving_license" | "vehicle_registration" | "vehicle_insurance" | "vehicle_photo";
            storage_ref: string;
            /** Format: uuid */
            vehicle_id?: string | null;
            /** @enum {string} */
            status: "pending" | "verified" | "rejected" | "superseded";
            /** Format: date */
            issued_at?: string | null;
            /** Format: date */
            expires_at?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            reviewed_by?: string | null;
            rejection_reason_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DocumentSubmission: {
            /** @enum {string} */
            document_type: "national_id" | "driving_license" | "vehicle_registration" | "vehicle_insurance" | "vehicle_photo";
            /** @description مرجع المخزن فقط؛ إبقاء المحتوى خارج الخدمة يحد من نسخ البيانات الحساسة وتسرّبها إلى السجلات. */
            storage_ref: string;
            /** Format: uuid */
            vehicle_id?: string | null;
            /** Format: date */
            issued_at?: string | null;
            /** Format: date */
            expires_at?: string | null;
        };
        DocumentReview: {
            /** @enum {string} */
            decision: "verified" | "rejected";
            reviewed_by: string;
            rejection_reason_code?: string;
        } & (unknown & unknown);
        AvailabilityUpdate: {
            /** @enum {string} */
            declared_availability: "available" | "offline";
        };
        SuspensionRequest: {
            reason_code: string;
        };
        EligibilityView: {
            wasla_public_id: components["schemas"]["WaslaPublicId"];
            /** @enum {string} */
            eligibility_state: "eligible" | "ineligible" | "suspended" | "unknown";
            /** @description أكواد ثابتة لا نصوص؛ الكود يُحصى ويُقارن بعد تغيّر لغة الرسائل. */
            reason_codes: string[];
            policy_version: number;
            /** Format: date-time */
            evaluated_at: string;
        };
        EligibilityTickResult: {
            rechecked_drivers: number;
            changed_drivers: number;
            published: number;
            publish_failures: number;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            persistence: "postgres" | "memory";
            /**
             * Format: date-time
             * @description آخر نبضة أهليّة نُفّذت في هذه العمليّة، و`null` قبل أولى النبضات. أُضيف في Phase 05 ·
             *     MR 4/6 لا تحسيناً بل **مطابقةً لـADR-012 القرار 5**: الزمن نبضة لا مؤقّت، وغياب
             *     المُنادي الدوريّ (Phase 09) **فشل صامت**: وثيقة تنتهي ولا يُكتشف انتهاؤها ولا يشتكي
             *     أحد. الحقل مؤشّر ذلك الغياب، وإغفاله في MR 1/6 كان عيباً في العقد لا قراراً: القرار
             *     سمّى الحقل بالحرف، والطور 07 سبق أن نشر سابقته في `/health` للإرسال.
             *     وهو **مؤشّر عمليّة لا حالة مخزّنة**: إعادة التشغيل تُعيده إلى `null` لأن المقيس هنا
             *     «أيجري النقر على هذه العمليّة؟» لا «متى نُقر آخر مرّة في التاريخ» — والأخير محلّه
             *     `eligibility_recheck_at` في القاعدة.
             */
            last_tick_at: string | null;
        };
        ErrorResponse: {
            error: {
                /** @description كود ثابت؛ يتعاقد المستهلك على الكود لا على ترجمة الرسالة. */
                code: string;
                message: string;
                /**
                 * @description تفاصيل بنيوية بلا إعادة قيمة المدخل؛ القيمة في رسالة خطأ تعيش في سجلات أوسع صلاحية.
                 *     الحقول **معدودة** لا حقيبة حرّة، وذاك بعينه ما يمنع «ضع القيمة في التفاصيل»:
                 *     `field` يسمّي الحقل ولا يردّ ما كُتب فيه. أُعلنت الحقول في Phase 05 · MR 4/6 لأن
                 *     `additionalProperties: false` بلا `properties` في MR 1/6 يعني **لا مفتاح مسموح**،
                 *     فكل تفصيل يرسله الخطأ كان سيُفشل تحقّق مستهلك صارم على استجابةٍ صحيحة.
                 */
                details?: {
                    /** @description اسم الحقل المرفوض لا قيمته. */
                    field?: string;
                    /** @description وصف الشكل المتوقّع أو الانتقال المرفوض. */
                    expected?: string;
                    /** @enum {string} */
                    document_type?: "national_id" | "driving_license" | "vehicle_registration" | "vehicle_insurance" | "vehicle_photo";
                    policy_version?: number;
                    /**
                     * @description اسم قيد القاعدة الذي كان سيرفض الكتابة نفسها؛ يجعل خطّ الدفاع الثاني قابلاً
                     *     للعثور بدلاً من افتراض أن القاعدة تعيش في TypeScript وحدها.
                     */
                    constraint?: string;
                };
            };
            trace_id: string;
        };
    };
    responses: {
        /** @description مدخلات غير صالحة شكلياً أو `Idempotency-Key` مفقود */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description ملف الدور أو المورد التابع غير موجود */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description تعارض في الحالة أو في إعادة استعمال مفتاح التفرّد */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description مدخل صالح شكلياً ومرفوض بقاعدة أعمال أو مرجع خارجي */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description الخدمة أو الاستمرارية في وضع متدهور */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        WaslaPublicId: components["schemas"]["WaslaPublicId"];
        VehicleId: string;
        DocumentId: string;
        /** @description إلزامي على الإنشاء والنبضة لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تكرر أثرها. */
        IdempotencyKey: string;
        /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerDriver: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على الإنشاء والنبضة لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تكرر أثرها. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverRegistration"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — يُعاد الملف نفسه بلا إنشاء ثانٍ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            /** @description أُنشئ ملف الدور */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    tickDriverEligibility: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على الإنشاء والنبضة لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تكرر أثرها. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description اكتملت النبضة، وقد تكون العدّادات صفراً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityTickResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDriver: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ملف الدور */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    patchDriver: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverProfilePatch"];
            };
        };
        responses: {
            /** @description الملف بعد التعديل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDriverZones: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المناطق، مرتّبة من الرتبة الأولى إلى الأخيرة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceZoneList"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    replaceDriverZones: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description قائمة كاملة مرتّبة تصاعدياً حسب `preference_rank`؛ تتحقق الخدمة من التتابع والفرادة. */
                    zones: {
                        zone_id: components["schemas"]["ZoneRef"];
                        preference_rank: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description المناطق بعد الاستبدال */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceZoneList"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDriverVehicles: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description المركبات مرتّبة بالأقدم إضافةً أولاً */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        vehicles: components["schemas"]["Vehicle"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    registerDriverVehicle: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على الإنشاء والنبضة لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تكرر أثرها. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRegistration"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجّل سابقاً — تُعاد المركبة نفسها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description أُضيفت المركبة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    patchDriverVehicle: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
                vehicleId: components["parameters"]["VehicleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehiclePatch"];
            };
        };
        responses: {
            /** @description المركبة بعد التعديل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listDriverDocuments: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الوثائق بما فيها المستبدلة حتى يبقى التدقيق قابلاً للقراءة */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        documents: components["schemas"]["DriverDocument"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    submitDriverDocument: {
        parameters: {
            query?: never;
            header: {
                /** @description إلزامي على الإنشاء والنبضة لأن إعادة المحاولة بعد انقطاع الشبكة لا يجوز أن تكرر أثرها. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentSubmission"];
            };
        };
        responses: {
            /** @description نفس مفتاح التفرّد سُجل سابقاً — تُعاد الوثيقة نفسها */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDocument"];
                };
            };
            /** @description سُجلت الوثيقة بانتظار المراجعة */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDocument"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reviewDriverDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentReview"];
            };
        };
        responses: {
            /** @description الوثيقة بعد القرار */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDocument"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateDriverAvailability: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityUpdate"];
            };
        };
        responses: {
            /** @description الملف بعد تسجيل الإعلان */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    suspendDriver: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuspensionRequest"];
            };
        };
        responses: {
            /** @description الملف بعد الإيقاف */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reinstateDriver: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الملف بعد إعادة التفعيل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDriverEligibility: {
        parameters: {
            query?: never;
            header?: {
                /** @description يصبح `trace_id` في الخطأ؛ فصل التتبع عن حمولة العمل يمنع أن يصير المعرف دليلاً تجارياً. */
                "x-request-id"?: components["parameters"]["RequestId"];
            };
            path: {
                waslaPublicId: components["parameters"]["WaslaPublicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description نتيجة آخر حساب للأهلية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityView"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حالة الخدمة وطبقة الاستمرارية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
